### ISSUE TITLE
@model cannot overwrite function definition

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#101]

**Comment by xukai92** [comment]
### Note 1

I've located this issue. It actually results from something about our mechanism to run the sampler.

My method to locate the issue is shown below:

```
using Distributions, Turing

@model modelname() = begin
  x ~ Normal(10, 2)
  return(x)
end

chain = @sample modelname() HMC(1000, 0.5, 2)
#chain2 = @sample modelname() SMC(1001)
#chain3 = @sample modelname() PG(10,11)
mean(chain[:x])
#mean(chain2[:x])
#mean(chain3[:x])
```

I change the model each time I run a chain, and I observe that chains created by a new type of sampler is able to use the new model.

**Comment by xukai92** [comment]
### Cause of issue

See the snippet below for the cause

```
runmodel(model) = model()
model() = 1
runmodel(model) # => 1
model() = 2
runmodel(model) # => 1
```

Passing the name of function call and using this function call seems to be somehow cached (or just an immutable object which lose its reference when it is redefined).

**Comment by xukai92** [comment]
### Update

I ask this problem to Julia team via Gitter and get this reply:

> https://github.com/JuliaLang/julia/issues/265
It's been fixed in 0.6
On 0.5, there really is no clean solution

**Comment by yebai** [comment]
Here is a trick that can get around the problem

```julia
runmodel(model, _) = model()
model() = 1
runmodel(model, Val{rand()}()) # => 1
model() = 2
runmodel(model, Val{rand()}()) # => 2
```

**Comment by xukai92** [comment]
@yebai That's awesome! Many thanks!

**Comment by xukai92** [comment]
Closed by https://github.com/yebai/Turing.jl/pull/134
