### ISSUE TITLE
A bug in Gibbs sampler

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#102]
When copying the variables generated by PG to varInfo, the helper function doesn't deal with arrays correctly. It is because the output of PG stores array variables as keywords in a dictionary but HMC store the flatten version, i.e.

```
arr = [1,2,3]
```

in varInfo are 3 entries `arr[1]`, `arr[2]`, and `arr[3]`.

**Comment by xukai92** [comment]
This is actually related to #96. Maybe we can have a meeting on these issues.

**Comment by yebai** [comment]
Let's talk about this tomorrow.

**Comment by yebai** [comment]
Fixed by PR #103
