### ISSUE TITLE
Turing Interface Design

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#104]
This is an umbrella issue  about Turing's front-end syntax design.

- Language syntax #55 
- Sampling syntax ##139 #82 #107

Some related issues about Turing's internal design

- MCMC sampling state: #96

**Comment by yebai** [comment]
Our current modelling and inference syntax allows the user to specify observations through the `model` macro; the actual data is passed to the model when calling the `sample` function, eg.

```julia
@model gdemo(x) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x[1] ~ Normal(m, sqrt(s))
  x[2] ~ Normal(m, sqrt(s))
  return s, m
end

sample(gdemo([1.0, 2.0]), HMC(..))
```

Some limitations with this design

- we need to modify the model when data is changed (eg. we want to turn `m` into data).
- lack of support for functions such as 
  - `gradient(gdemo(s = 1, m= 0, x =[1.0, 2.0]))`
  -  `logpdf(gdemo(s = 1, m= 0, x =[1.0, 2.0]))`

However, it seems we can further improve the compiler so that user can define models in the following way

```julia
@model gdemo() = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x[1] ~ Normal(m, sqrt(s))
  x[2] ~ Normal(m, sqrt(s))
  return s, m
end

# Once the model is defined, we can generate multiple different realisations of 
#  the model through passing in different variables, eg.

# here `x` is observed, `s` and `m` are parameters
f1 = gdemo(x = [1.0, 2.0])

# here `x` and `m` are observed, `s` is a parameter
f2 = gdemo(x = [1.0, 2.0], m = 0.0)

 # here data is a dictionary that contains all the observed variables (eg. x, m)

f3 = gdemo(data=data)

# sampling
sample(g1, HMC(..)) # sample from g1
sample(g2, HMC(..)) # sample from g2

# computing gradients
gradient(gdemo(x = [1.0 2.0], m = 1.0, s = 1.0))

# computing log probability (requires passing in all random variables)
logpdf(gdemo(x = [1.0 2.0], m = 1.0, s = 1.0))
```

This improved compiler could substantially simple the `gradient` inference (#97) , make models defined in Turing more compatible with interfaces from Distributions package (eg. we can support `logpdf` function, hence start supporting nested models #86).

**Comment by xukai92** [comment]
Great design!

BTW. Shall we close the old design #55?

**Comment by xukai92** [comment]
TODO:
- [ ] doc these changes.

**Comment by yebai** [comment]
@xukai92 Can we move these design discussions on language syntax and sampling interface to the wiki?

**Comment by xukai92** [comment]
Closed by adding corresponding discussion to wiki.
