### ISSUE TITLE
Sampler (internal) interface design

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#107]
This current sampler design is a bit out-of-date. Many functions interfaces are created without considering the compositional sampler interface (i.e. when used as a step in Gibbs). This leads to a slightly messy situation that we need to have separate functions for each sampler (e.g. PG, HMC), one for direct use as a sampler, one for use as a step in a Gibbs sampler. Therefore, it makes sense to re-consider the issue of internal sampler interfaces. 

A possible new design is as follows

```julia

@model mdemo() = begin ... end

# internal sampler interface

v2 :: VarInfo = mdemo( v:: VarInfo, s :: Sampler)

```

With this internal sampler interface, both standalone and compositional uses of sampler can be relatively easily implemented as a thin wrapper, e.g. 

```julia

function run(mdemo, g :: Gibbs)

  v0 = mdemo() # initialise v0 by sampling from the prior
  v1 = step(mdemo, v0 :: VarInfo, s1 :: Sampler) # e.g. s1 is HMC
  v2 = step(mdemo, v1 :: VarInfo, s2 :: Sampler) # e.g. s2 is PG

end

```

Note that here `VarInfo` also contains data that is passed to `mdemo` (see #96).

**Comment by yebai** [comment]
It is possible to remove the use of macro for `sample` by parsing each model into a function that returns a function. For example

```julia

@model mdemo(x,y) = begin
 # some code
end


f = mdemo(x,y)  # `f` is a function in the form of: `f(vi = VarInfo(), spl = ImportanceSampler(..))`
sample(f, PG(10,10))
```

Some other (advanced) use of this syntax are

```julia
f = mdemo(x,y)
vi = f() # produce a sample (i.e. `vi::VarInfo`) from the prior, with `vi.logjoint` set to the importance weight.

vi2 = f(vi::VarInfo, spl::Sampler) 

```

**Comment by xukai92** [comment]
NOTE: https://github.com/yebai/Turing.jl/issues/101 could also be solved by this PR.

**Comment by xukai92** [comment]
Closed by https://github.com/yebai/Turing.jl/pull/134

**Comment by yebai** [comment]
There is a bit un-finished work in this PR, so I'm re-opening it. Briefly, I plan to add the following interface

```julia
sample(mdemo(), data= somedata, sampler)
```

**Comment by yebai** [comment]
- [ ] Modify samplers: `vi_new = step(model, vi = vi_old, sampler = spl)`
