### ISSUE TITLE
`unflatten` for Mamba Chain

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#111]
In order to support better access to Mamba Chain data structures, we can support the following interface

```julia

c # Mamba Chain
c[:x, sim=1] # Return all samples that has a name starting with `x`, e.g. `x[1][1]`.
c[i, sim=1] # Return the `i`'th sample containing all parameters, 
                     # i.e. in the format of `Dict{Symbol, Any}, where the key is like `:x`. 
```

EDIT (22 Mar 2017): add `c[i, sim=1]`.

**Comment by xukai92** [comment]
Strictly saying, `c[:x]` should return all samples has a **heading symbol** equal to `x`. This distinguishs some variables who is a leading substring of others, e.g. if `x[*]` and `x1[*]` both exist, `c[:x]` only returns `x[*]`.

**Comment by yebai** [comment]
This has now been supported through storing samples in both `Turing` and `Mamba` format (PR #116).
