### ISSUE TITLE
vectorising likelihood computations

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#117]
There are certain cases where the efficiency of HMC sampler can be substantially improved, such as the following example

```julia
@model nbmodel begin
  theta ~ Dirichlet(alpha)
  phi = Array{Any}(K)
  for k = 1:K
    phi[k] ~ Dirichlet(β)
  end
  for m = 1:M
    z[m] ~ Categorical(theta)
  end
  for n = 1:N
    w[n] ~ Categorical(phi[z[doc[n]]])
  end
  phi
end
```
(The full model can be found [here](https://github.com/yebai/Turing.jl/blob/master/example-models/naive-bayes/model.jl))

If we introduce a vectorising notation, the likelihood computation step can be re-written as

```julia
@model nbmodel begin
  theta ~ Dirichlet(alpha)
  phi = Array{Any}(K)
  for k = 1:K
    phi[k] ~ Dirichlet(β)
  end
  z ~ Categorical(theta)                     #  z[m] ~ Categorical(theta)
  w ~ [Categorical(phi[z[doc[n]]) for n=1:n] # w[n] ~ Categorical(phi[z[doc[n]]])
  phi
end
```

The reason that vectorising code can be more efficient is due to improved automatic differentiation and inefficiency associated with loops.

Reference: [Stan documentation](https://github.com/stan-dev/stan/releases/download/v2.14.0/stan-reference-2.14.0.pdf) (see the section 4.2)

**Comment by yebai** [comment]
Ref: #255

**Comment by xukai92** [comment]
Do we also want to support observations of multivariate distributions for data with nested-arrays?
