### ISSUE TITLE
The format of uid need to be enriched

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#122]
Agreed format:

`"x{##720:1}[1][1,2]..."`,

where `#720` is generated by `gensym()`, `1` after `:` is the counter.

**Comment by xukai92** [comment]
### Discussion

Do you think it's better to re-arrange the format to be `"{##720,x[1][1,2]...}:1"`? 

The reason I feel it's better is that it clearly shows that we are counting the unique set, {gensym(), flattened naming}.

**Comment by yebai** [comment]
we can do that, but maybe have some utilities to easily parse it into a tuple (e.g. `(##720,1,x, [1][1,2]...)`).

**Comment by xukai92** [comment]
Make sense. I think tuples are faster than strings. Is this right?

**Comment by yebai** [comment]
might be, since tuples are stored on the stack

**Comment by xukai92** [comment]
Closed by PR #128
