### ISSUE TITLE
Summarise `Chain` in `io.jl`.

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#13]
The current `Chain` type dump all fields to the console by default. A potential better way is to Summarise the results, e.g. print the `mean` and `variance`. This can be done by using the [weighted](http://statsbasejl.readthedocs.io/en/latest/means.html#mean) `mean` function etc in the [StatsBase](http://statsbasejl.readthedocs.io/en/latest/weightvec.html) package.

**Comment by evsmithx** [comment]
Resolved in #17
