### ISSUE TITLE
Run models in Stan (or other PPLs) in benchmark script as well

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#131]
I feel it's good to run some models in other PPLs as well to see the difference in running time.

**Comment by yebai** [comment]
This sounds good; it should be relatively simple to add Stan models to `benchmark\benchmarks.jl`.

**Comment by yebai** [comment]
Maybe we can start by adding Stan versions of the `bernoulli` and `simplegauss`? 

It is possible to add Stan version of the `simplemixture` model, but we will need to modify the model in a way such that cluster indicators are analytically marginalised out.

**Comment by xukai92** [comment]
Sure. The `simplemixture` one is actually adapted from a Stan code. I guess the Stan one did that by https://github.com/stan-dev/example-models/blob/master/basic_estimators/normal_mixture.stan#L24#L27?

BTW what's the correct way to install CmdStan on Travis?

**Comment by yebai** [comment]
> BTW what's the correct way to install CmdStan on Travis?

There might be already an `apt-get` package; also the following script might be helpfull

https://gist.github.com/lindemann09/5bead1ce0320974ac4f6

**Comment by yebai** [comment]
Closed by PR #150;
Other tasks are now in #151
