### ISSUE TITLE
Support explicit return statement

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#132]
```julia
@model example() = begin
  x = 1
  return x
end
```

i.e. didn't use `@~`

should still be supported.

**Comment by yebai** [comment]
Maybe we can 

- restrict the user to write only `return x::Symbol`, but not `return x+1`.
- construct a special `VarInfo` that also stores variables referenced in the `return` statement.
- later in `Sample(vi::VarInfo)`, only extract variables referenced in the `return` statement.
