### ISSUE TITLE
Depreciate `Void` in `observe`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#135]
The following line uses a `Void` type to handle cases where sampler is `null`

https://github.com/yebai/Turing.jl/blob/master/src/samplers/hmc.jl#L141

It is better to have a more principled mechanism to handle such cases.

**Comment by xukai92** [comment]
It this related to https://github.com/yebai/Turing.jl/issues/126?

**Comment by yebai** [comment]
Yes, they are related. But `observe` needs some additional treatment since it controls automatic differentiation.

**Comment by xukai92** [comment]
What do you mean by "it controls automatic differentiation"?

**Comment by yebai** [comment]
I mean this `observe` function is needed by `gradient`, since inside `observe` we need to turn some variables into `Dual` types. Strictly speaking, we don't need to do this when sampling from the prior, but it is needed if we want to compute gradients.
