### ISSUE TITLE
model in ParticleSampler

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#137]
`ParticleSampler` still has a field named model. I guess we can remove it now?

**Comment by yebai** [comment]
yes, we can do that (if it doesn't have dependencies)

**Comment by yebai** [comment]
BTW: it is probably a good practise to start referencing issue IDs in commit comments.

**Comment by xukai92** [comment]
I see. Good suggestion!

**Comment by xukai92** [comment]
Implemented in #137
