### ISSUE TITLE
create and generalise `is_inside` test

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#149]
(NOT URGENT)

The current `inside` code (see [here](https://github.com/yebai/Turing.jl/blob/3ac05a4e19ead1e48a4e003fed68b39cecc46234/src/samplers/hmc.jl#L142
) for example) tests whether a symbol exist in `spl.space`, this won't work for elaborate cases. For example

```julia

# Example 1
spl.space = Set([:x, :y, :z])
is_inside(Symbol("x[1]"), spl)

# Example 2
spl.space = Set([Symbol("x[1]"), :y, :z])
is_inside(Symbol("x[1][1]"), :y, :z)
```

Such complicated cases may arise when a user uses an array to store many parameters, and associate this array's elements to different samplers (e.g. `HMC(Symbol("x[1]")`, `PG(Symbol("x[2]")`).

**Comment by xukai92** [comment]
Another thing related to this is that writing `Symbol("x[1]")` is very annoying. Maybe we can also just support calling things using strings? Like `chian["x"]` will do the same thing as `chain[:x]`, and the same for defining space.

**Comment by yebai** [comment]
It is possible to support `:(x[1])`. We need to check `:(x[1])==ref` though.

**Comment by xukai92** [comment]
I would propose that we converted user's input (e.g. `:(x[1])` in sampler algorithm definition like `HMC(..., :(x[1])`) into a `VarName`, so that we can use `vn.sym` to get `:x` easily.

However in this case, it's might be hard to determine if all variables are covered: users might only declare to sample some sub-dimensions of a variable?

**Comment by yebai** [comment]
Maybe we can start by separating the code into a function, then we can make the function more general.

**Comment by xukai92** [comment]
Closed by https://github.com/yebai/Turing.jl/pull/312
