### ISSUE TITLE
Improving the benchmark log

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#151]
After discussion, the key points we want to log in the benchmark are

- [x] Accuracy
  - Analytic solution v.s. Turing
  - Stan v.s. Turing
- [x] Running time
- [x] Memory allocation 
- [x] Statistics
  - lp
  - time for leapfrog integration
  - NOTE: this can be done in `Varinfo2Sample()`
  - NOTE 2: when implementing this, rename `Varinfo2Sample()` -> `Sample()`

**Comment by xukai92** [comment]
For the log-posterior, actually only HMC can report this. Maybe we can report log-p when using HMC and report log-evidence when using PG? Then what to do when using Gibbs?

**Comment by yebai** [comment]
Yes, `log-evidence` could work for PG.
Let's store log-posterior from the HMC step for Gibbs now, and change to something more sensible later.
