### ISSUE TITLE
remove obsolete `randoc`, `randc`?

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#156]
It is probably OK to remove the following references to `randc` 

https://github.com/yebai/Turing.jl/search?q=randoc&type=Code&utf8=%E2%9C%93

The main reason for having `randc` is to reduce memory allocation in particle filtering. However, storing all random variables doesn't seem to be a huge problem (?).

**Comment by xukai92** [comment]
I removed `randoc` when re-factoring `VarInfo`.
