### ISSUE TITLE
Add a tutorial in readme file

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#165]
- illustrate how to write a model
- how to run inference 
- how to summarize and visualise MCMC samples

**Comment by xukai92** [comment]
I think we can extend&update the http://turingjl.readthedocs.io/getstarted.html#a-short-tutorial and put it in the README.md

**Comment by yebai** [comment]
Actually, we've already have 1 and 2. We introduced some new features (e.g. `Mamba.Chains`) in 0.2. We wan to illustrate these features, in particular `describe(chain` and `plot(chain)`.
