### ISSUE TITLE
Particle filter samplers need to deepcopy `VarInfo` for each particle.

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#168]

**Comment by xukai92** [comment]
Can you explain it more? I think we do use `deepcopy` in `forkr` and `forkc`.

**Comment by yebai** [comment]
Yes, but  `VarInfo` are only deep copied when`resample` is called. Hence, all particles are sharing `VarInfo` until the first `observe` statement. Is that true in the current code?

**Comment by xukai92** [comment]
I see. In the start of each PG step, the `push` function will use the constructor of `TraceR` or `TraceC`, in which we also use `deepcopy`. But I notice there is a bug in the constructor (https://github.com/yebai/Turing.jl/blob/master/src/trace/trace.jl#L66), in which I pass the wrong `vi` to the model closure. I think this should be the cause of the issue.

**Comment by yebai** [comment]
Cool - I fixed this in my working PR.

**Comment by yebai** [comment]
I think this is why our `posterior` trick for `simplemixture` and `LDA` produces incorrect results.

**Comment by xukai92** [comment]
Cool.

Yes, that makes a lot of sense!

**Comment by yebai** [comment]
Fixed now.
