### ISSUE TITLE
ProgressMeter is not compatible with Jupyter notebook

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#171]
The new progress bar will cause Jupyter notebook halt (e.g. `BayesHmm`).

**Comment by xukai92** [comment]
May be there is something wrong inside Turing.jl which indeed runs for long?

**Comment by xukai92** [comment]
It seems that the ProgressMeter is actually ok? I tried few times it seems fine. I re-enabled it in https://github.com/yebai/Turing.jl/pull/310/commits/29af74d9a79b7104d7bd2b0fe8f4bdf76caf47ff. And let's see if it happens again.

My guess for previews halt is that the tuning may not converge thus cause iniftely long run.

**Comment by xukai92** [comment]
HMC actually works in the notebook. It seems that PG has some strange interaction between ProgressMeter? Any idea?

**Comment by xukai92** [comment]
@yebai I've located that the cause of this problem is the `resample!()` function, if which is removed the problem disappears.

**Comment by xukai92** [comment]
Update: `resample!` works if I use the flag `use_replay=true`
