### ISSUE TITLE
Re-define `~`: macro => function

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#173]
Julia 0.6 stopped supporting parsing `~` as a macro by default. We might need to perform this parsing in the `model` macro on our own and redefine `~` as a function.

**Comment by xukai92** [comment]
Comments from other developer: syntax sugar like `@model` and `~` is cool and good for end users but we should also make the plain function available (at least have a section "For Developers" to explain how to use them directly)

**Comment by yebai** [comment]
Relevant discussions on this matter: 

https://github.com/JuliaLang/julia/issues/4882

https://github.com/JuliaStats/GLM.jl/issues/116

**Comment by kleinschmidt** [comment]
StatsModels.jl handles `~` in a Formula as a function now: see https://github.com/JuliaStats/StatsModels.jl/pull/9

**Comment by yebai** [comment]
@kleinschmidt Thanks, I'll take a look at that. If you know how to port it to Turing, please get in touch.
