### ISSUE TITLE
Merge `ParticleSampler` and `HMCSampler` into `Sampler`?

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#174]
After introducing `VarInfo` and the new compiler interface, it seems possible to merge some sampler classes into a single one, e.g. 

```julia
type Sampler{T:<InferenceAlgorithm}
  alg            ::  T
  particles   ::  ParticleContainer
  samples   ::  Array{Sample}     
  info        :: Dict{Symbol,Any} # Stores other sampler data, e.g. chunksize in HMC.          
end
```

In addition, to query sampler specific information (e.g. gradient sampler, particle sampler), we might consider introduce the following generic APIs for sampler

```julia

require_gradient(s :: Sampler) = false
require_particles(s :: Sampler) = false


# Then for HMC, we redefine these functions
require_gradient(s :: Sampler{HMC}) = true

# PG, SMC, IS
require_particles(s :: Sampler{PG}) = true
require_particles(s :: Sampler{SMC}) = true
require_particles(s :: Sampler{IS}) = true
```

**Comment by xukai92** [comment]
This makes sense. I'm also thinking the new sampler should somehow make it easier for different samplers to share some basic functions like `assume()`, `rand()`, etc. instead of using `Union{}`

**Comment by xukai92** [comment]
This `data` dict would also be helpful for adaptive samplers as we need to pass/store adaptive parameters somehow.

**Comment by yebai** [comment]
We should consider store run time information in `sampler.info` as well, e.g. acceptance ratio, time per MCMC iteration, time per leapfrog iteration etc.

**Comment by xukai92** [comment]
I think it's bit weird that all samplers should have a filed of `particles   ::  ParticleContainer`. I think we should treat it same as `VarInfo`. Do you think we can remove this field? I briefly looked into PG and SMC codes and feel it should be OK.

**Comment by xukai92** [comment]
@yebai I'm sorry that I pushed my commits (for this issue) directly to the master by mistake. Can you have a look at them?
