### ISSUE TITLE
Make a new release Turing 0.2

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#177]
- Need to update RELEASES.md
- Register a new release in METADATA.jl

**Comment by xukai92** [comment]
Let's do https://github.com/yebai/Turing.jl/issues/165 as well before releasing 0.2

**Comment by xukai92** [comment]
PR for METADATA: https://github.com/JuliaLang/METADATA.jl/pull/8920

**Comment by yebai** [comment]
The list of PRs that we created in this release

https://github.com/yebai/Turing.jl/milestone/2?closed=1

Well done!

(I've also added some major PRs to [RELEASE.md](https://github.com/yebai/Turing.jl/blob/master/RELEASE.md))

**Comment by xukai92** [comment]
@yebai You mentioned you've put the license stuff for Mamba right? Shall we chase the release then?
