### ISSUE TITLE
Initial step size before heuristically search

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#183]
Another thing about the NUTS paper is that the initial step size before heuristically search is set to 1.0, which may already big enough to move too far in some constraint space to cause NaN. My current solution for this is to halve the initial 1.0 until there is no NaN, after which apply the heuristically search.

I see this idea in https://github.com/mfouesneau/NUTS/blob/master/nuts.py#L111 but I'm not 100% sure if this is OK.

**Comment by yebai** [comment]
Closed by #202
