### ISSUE TITLE
Implementation of the HMC sampler

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#19]
I'm gonna put issues about implementing the HMC sampler here.

One of them is about the compiler. I wonder why we convert the `@observe x ~ Distribution(params)` to the `logpdf()` statement in the compiler level instead of doing this inside the sampler?

It makes me hard to pass `Dual` type to my custom distribution wrapper in order to get the gradient information.

Do you think I need the amend the compiler or there is any other approach? @yebai

**Comment by adscib** [comment]
I'm pretty sure it was not intentional to do things this way. The right thing to do is modify the compiler to call the sampler-specific `observe` method, much like for `assume`, and do all the actual work there.

**Comment by xukai92** [comment]
I agree with you. I will amend the compiler to make them consistent.

**Comment by xukai92** [comment]
@yebai The implementation to replay priors I showed you last time is too naive. It fails when there is loop like

```
for i in 1:10
  @assume xs[i] ~ Normal(0, 1)
end
```

as the dictionary would store key of `xs[i]` literally.

I may try to solve this issue by letting the program pass key like `xs[1]` but I wonder can the `TArray` data structure solve this problem?

**Comment by adscib** [comment]
Thanks. Since it will probably take a while before HMC is incorporated into Turing, it would be great if you could submit a separate patch fixing the compiler that we can accept now.
