### ISSUE TITLE
julia-config error on Ubuntu 16.04

### ISSUE THREAD

**Issue by cscherrer** [yebai/Turing.jl#2]
On Ubuntu 16.04, starting with a fresh Julia install, I'm getting the following error. Could there be an undocumented dependency?

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

julia> Pkg.update
update (generic function with 1 method)

julia> Pkg.update()
INFO: Initializing package repository /home/chad/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("Turing")
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of ConjugatePriors from git://github.com/JuliaStats/ConjugatePriors.jl.git
INFO: Cloning cache of Distributions from git://github.com/JuliaStats/Distributions.jl.git
INFO: Cloning cache of PDMats from git://github.com/JuliaStats/PDMats.jl.git
INFO: Cloning cache of StatsBase from git://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of StatsFuns from git://github.com/JuliaStats/StatsFuns.jl.git
INFO: Cloning cache of Turing from git://github.com/yebai/Turing.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing Compat v0.7.14
INFO: Installing ConjugatePriors v0.1.2
INFO: Installing Distributions v0.8.9
INFO: Installing PDMats v0.3.6
INFO: Installing StatsBase v0.8.0
INFO: Installing StatsFuns v0.2.0
INFO: Installing Turing v0.0.1
INFO: Building Turing
ERROR: could not open file /usr/share/julia/julia-config.jl
ERROR: could not open file /usr/share/julia/julia-config.jl
ERROR: could not open file /usr/share/julia/julia-config.jl
gcc  -O2 -shared -fPIC task.c   -o libtask.so
task.c:6:19: fatal error: julia.h: No such file or directory
compilation terminated.
Makefile:9: recipe for target 'task' failed
make: *** [task] Error 1
===============================[ ERROR: Turing ]================================

LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
while loading /home/chad/.julia/v0.4/Turing/deps/build.jl, in expression starting on line 1

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Turing had build errors.

 - packages with build errors remain installed in /home/chad/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Turing")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
```

**Comment by adscib** [comment]
How did you install Julia? We rely on a directory layout used by precompiled distributions. If you build from source julia-config.jl ends up in a different place and our script for building dependencies can't find it.

If you want to build Julia from source, I believe there is an option to create a tarball, although I can't find it at the moment. If you use that then Turing should work. Another option would be to edit deps/Makefile in Turing. Just set JL_SHARE to the directory containing julia-config.jl.

**Comment by cscherrer** [comment]
I just did `sudo apt-get install julia`. Shouldn't be anything unusual.

**Comment by adscib** [comment]
Can you show me the output of
``ls `julia -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))'` ``

**Comment by cscherrer** [comment]
```
$ ls `julia -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))'`
base  test
```

**Comment by adscib** [comment]
OK, thanks. Looks like we have portability issues with our dependencies. We'll fix that as soon as possible. I don't have access to an Ubuntu machine right now, so if you want a quick fix the best I can offer you at the moment is the following.

Find the julia-config.jl file. Should be somewhere in the directory where Julia is installed. Then go to ~/.julia/v0.4/Turing/deps/ and edit Makefile line 2:
`JL_SHARE=PATH_TO_JULIA_CONFIG`
Then try running `Pkg.build("Turing")` inside Julia.

**Comment by cscherrer** [comment]
After this it still complained about missing header files. I finally got it to build by uninstalling Julia and using [the PPA](https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases) instead.

**Comment by adscib** [comment]
I'm glad to hear you eventually found a way to run it.

@yebai do you have any ideas what we could do about this problem?

**Comment by yebai** [comment]
This issue seems to be related with Ubuntu's customised build of Julia. I don't know how to fix this without a Ubuntu machine, and I am not sure we should fix it. We could recommend all developers to install Julia from Julia's official [release website](http://julialang.org/downloads/).

**Comment by yebai** [comment]
We can con
