### ISSUE TITLE
Stochastic Gradient Hamiltonian Monte Carlo

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#201]
Maybe good to do it after NUTS. Also I guess we can combine it with https://github.com/yebai/Turing.jl/issues/189?

**Comment by emilemathieu** [comment]
Hello @xukai92 !
I have almost finished implementing SGHMC and SGLD, yet I have 3 questions:
- Should I fork the repo and create a pull request from my fork ?
- How can get the size of the batch ? (so as to adapt the learning rate)
- Can we sub-sample, i.e. use mini batch ?

**Comment by yebai** [comment]
Hello @emilemathieu 

> Should I fork the repo and create a pull request from my fork ?

Yes please. 

> How can get the size of the batch ? (so as to adapt the learning rate)

We haven't decided how to organise the interface for sub-sampling MCMC methods. Perhaps a starting point is to pass the batch size as a parameter to sampler (e.g. `spl.info`)?

> Can we sub-sample, i.e. use mini batch ?

Turing does not yet have interface for sub-sampling data, so feel free to create yours. Perhaps you can overload the vectorised likelihood notation (`x ~ [Dist]`, assuming x is i.i.d distributed as Dist) to perform sub-sampling

```julia
x = # big data array
 
@model gdemo(x) = begin
   s ~ InverseGamma(2,3)
   m ~ Normal(0,sqrt(s))
   # overload `observe` to perform sub-sampling, see -
   # https://github.com/yebai/Turing.jl/blob/master/src/samplers/hmc.jl#L195
   x ~ [Normal(m, sqrt(s))] 
   return s, m
end

chain = sample(gdemosgld(x), SGLD(...)) 
```

**Comment by emilemathieu** [comment]
Assuming x is i.i.d distributed as Dist (`x ~ [Dist]`) is very limiting I think. One (ugly ?) way is the following:

```julia
@model lr_nuts(x, y, d, n, σ²) = begin
  α ~ Normal(0, σ²)
  β ~ MvNormal(zeros(d), σ² * ones(d))
  for i = 1:10 # batch size
    j = rand(1:n)
    y′ = logistic(α + dot(x[j,:], β))
    y[j] ~ Bernoulli(y′)
  end
end
```

However, by doing so, we cannot adapt the learning rate w.r.t. the batch size.

**Comment by yebai** [comment]
> Assuming x is i.i.d distributed as Dist (x ~ [Dist]) is very limiting I think. One (ugly ?) way is the following

Yes, the i.i.d assumption is annoying. The loop-style syntax works for me at the moment. We could re-visit this syntax when new ideas are proposed.

**Comment by emilemathieu** [comment]
Merged https://github.com/yebai/Turing.jl/pull/327
