### ISSUE TITLE
HMC: better `leapfrog` function - partial hamiltonian trajectory

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#202]
The HMC family samplers occasionally runs into regions with `0` density. It is helpful to be able to `reject` and restart the current Hamiltonian simulation when this happens.

**Comment by yebai** [comment]
@xukai92 can you add the `reject` step for `NUTS` and `eNUTS`?

**Comment by xukai92** [comment]
Sure. Do you want me to do that in the current PR?

**Comment by yebai** [comment]
Yes, let's push to the same PR.

**Comment by yebai** [comment]
- [ ] Merge eNUTS and NUTS
- [ ] Implement `reject` for NUTS.

**Comment by yebai** [comment]
The current `leapfrog` code either returns a new simulation with total trajectory length (`τ * ϵ`), or reject the whole simulation.

```julia
leapfrog(_vi, _p, τ, ϵ, model, spl)
```

Instead of simply rejecting a (whole) simulation, perhaps we should improve the `leapfrog` function, so that `partial` valid simulation (e.g. `trajectory_length <=  τ * ϵ`can be returned.
