### ISSUE TITLE
HMC: transform variables on demand.

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#203]
The `link` and `invlink` functions will lose precision when called often. Perhaps it is better to implement an interface for `VarInfo` that will transform variable (back to constrained space) only on demand.

**Comment by xukai92** [comment]
I think the current `link(vi::VarInfo)` and `invlink(vi::VarInfo)` (in the `helper.jl` file) do this job. But the problem is that in order to use the variable in the model (i.e. run the model), the variable has to be transformed back, so `rand()` is designed to return values in the original domain.
