### ISSUE TITLE
Remove `find_logjoint`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#205]
It seems that we can remove the function `find_logjoint` below since `VarInfo.logjoint` always keep the logjoint?

https://github.com/yebai/Turing.jl/blob/b69b79912840a50f9fe3e046f3db574f7b21ffff/src/samplers/support/hmc_core.jl#L69

**Comment by xukai92** [comment]
`find_logjoint` is also reponsible to run the model once so that we can get the updated `logjoint`. But this function is only used in `find_H`. It makes sense that we merge them?

**Comment by yebai** [comment]
OK, let's merge them.

**Comment by yebai** [comment]
Addressed by #221.
