### ISSUE TITLE
Remove predict

### ISSUE THREAD

**Issue by adscib** [yebai/Turing.jl#21]
This is a suggestion from Brooks, which I support, to remove `@predict` in favour of standard `return`. It accomplishes the same goal without introducing new syntax. Also the experience of Anglican team indicates that people often associate `@predict` with the posterior predictive distribution, which is clearly not what it is.

**Comment by yebai** [comment]
It is OK to rename it, any ideas?

**Comment by xukai92** [comment]
`@request` or `@output` sound more natural for the purpose of this macro.

**Comment by adscib** [comment]
Renaming is certainly possible, but do we need this macro at all? Can't we
just use return?

Adam
