### ISSUE TITLE
Use generic type constants instead of manually written

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#215]
We should gradually change things like `1.0` to `one(T)`.

**Comment by yebai** [comment]
Good suggestion!

**Comment by xukai92** [comment]
Record: this commit https://github.com/yebai/Turing.jl/pull/233/commits/ce94f195df69a6ed9ab2484e6a9b9601b1d37333 improves generic typing for `transforms.jl` and `utli.jl`

**Comment by xukai92** [comment]
We have already done a lot on this and since in https://github.com/yebai/Turing.jl/issues/293 we need to do the typing refactoring anyway so I'm going to close this issue.
