### ISSUE TITLE
Unify numerical tests

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#217]
Better to unify numerical tests using a function like

```julia
check_numerical(chain, variables, exact, eps, strict) = begin
   ...
end
```

and use it by

```julia
check_numerical(res, [:s, :m], [49/24, 7/6], 0.1, false)
```

If `strict` is set to `true` `@test` will be used and throw error when test fails.

**Comment by yebai** [comment]
That makes sense. We can also do something similar to benchmark, e.g. create a special build on travis that perform numerical tests. This would allow us to separate numerical tests from common unit tests.
