### ISSUE TITLE
Make accumulating of log weight more roboust

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#218]
Our simple normal mixture below is broken

```julia
@model nmmodel(y) = begin
  N = length(y)

  theta ~ Uniform(0, 1)

  mu = tzeros(Dual, 2)
  for i = 1:2
    mu[i] ~ Normal(0, 10)
  end

  k = tzeros(Int64, N)
  for i = 1:N
    k[i] ~ Categorical([theta, 1.0 - theta])
  end

  for i = 1:N
    y[i] ~ Normal(mu[k[i]], 1.0)
  end
```

simply because here we set ` mu = tzeros(Dual, 2)`: then `logp` is `Dual{Float64, 0}` and we call `Float64(logp)` in container, of which the conversion is not supported (and the customed conversion is removed from Turing). 

Of course users can define the same vairbale as `mu = tzeros(Real, 2)`, which will also work. But I guess we should also support that.

**Comment by xukai92** [comment]
I now manually check if `logp` is `Dual` and convert it back to `Real` (commit https://github.com/yebai/Turing.jl/commit/3c2e2b5545f3a76554000edaa3533580e2fd3ad8). Do you think it's good enough or it's better to use `Real` for accumulating of log weight?

**Comment by yebai** [comment]
Yes, that works.
