### ISSUE TITLE
Improve `gradient(vi, model, spl)`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#225]
Our current `gradient` code perform chunk-mode auto-diff in vivo. Perhaps we can simplify our own code through defining the following function

```julia

f(x::Vector) = begin
  vi[spl] = x
  lp = find_lp(model, vi, spl)
end
```

Then

```julia
x = vi[spl]
g = x -> ForwardDiff.gradient(f, x); # g = ∇f
```

This would allow us to reuse the `gradient` function from `ForwardDiff` and remove our own code for managing dual chunks.

Reference: https://github.com/JuliaDiff/ForwardDiff.jl

**Comment by xukai92** [comment]
Sounds good! Let's do this!
