### ISSUE TITLE
Reduce `deepcopy` for `VarInfo`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#237]
The current implementation of HMC/NUTS contains many calls to `deepcopy` for `VarInfo`. This substantially increases memory allocation and may deteriorate performance. Perhaps we can share the same `VarInfo` between `leapfrog` iterations that belong to a single HMC/NUTS proposal (or sample).

**Comment by yebai** [comment]
TODOs

- [ ] Create separate builds for `LDA` and `MoC`, so that we can record performance changes for every commit.

**Comment by xukai92** [comment]
What does "create separate builds" mean?

**Comment by yebai** [comment]
At the moment, we have `benchmark.jl` and `runtests.jl` on Travis. Perhaps we should separate `lda.run.jl` and `moc.run.jl` into separate builds so that we don't exceed the build time limits imposed by Travis.

**Comment by xukai92** [comment]
I see!

**Comment by xukai92** [comment]
Resolved in https://github.com/yebai/Turing.jl/pull/254
