### ISSUE TITLE
Old notebooks

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#238]
Shall we also move old notebooks (https://github.com/yebai/Turing.jl/tree/master/doc/source/notebooks) to https://github.com/yebai/Turing.jl/tree/master/example-models/notebooks?

**Comment by yebai** [comment]
That makes sense. We can also remove some obsolete models.

**Comment by xukai92** [comment]
Closed by https://github.com/yebai/Turing.jl/pull/321
