### ISSUE TITLE
ddistribution bug

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#24]
The HMC branch introduces a bug to the compiler, basically the `assume` macro converts all distributions to ddistribution type. This causes problems for distributions without corresponding distribution type.

**Comment by xukai92** [comment]
I use the same way you did in [Fix ddistribution issue](https://github.com/yebai/Turing.jl/commit/93d39209a2c8029c7933a02451463b52e9befb10) but also do the same for `@observe`.

I tested it by writing a model with a undefined dDistribution type, which works now.
