### ISSUE TITLE
errors in examples.

### ISSUE THREAD

**Issue by AIAdventures** [yebai/Turing.jl#256]
![image](https://cloud.githubusercontent.com/assets/26102503/26048968/a97a1a6c-399c-11e7-908b-2fe1b146cb3e.png)

**Comment by AIAdventures** [comment]
hi great package!
Trying some examples and getting errors.
Best,
Andrew

**Comment by yebai** [comment]
Hi, the `@sample` macro has been re-implemented as a function. Try

```julia
using Turing, Distributions

@model gdemo(x) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x[1] ~ Normal(m, sqrt(s))
  x[2] ~ Normal(m, sqrt(s))
  return s, m
end

c3 = sample(gdemo([1.5, 2]), HMC(1000, 0.1, 5))

describe(c3)
```

Also, Turing is now using [ProgressMeter](https://github.com/timholy/ProgressMeter.jl) to display progress information. ProgressMeter does not seem to interact with Jupyter notebook very well. I would recommend running the example from terminal for the moment. However, if you know how to make ProgressMeter work with Jupyter notebook, please let us know.

**Comment by AIAdventures** [comment]
ah so should i redo my git clone?

**Comment by AIAdventures** [comment]
and re download the package :)

**Comment by AIAdventures** [comment]
amazing package btw really awesome!
is the parallel sequential monte carlo implemented?
Best,
Andrew

**Comment by yebai** [comment]
> amazing package btw really awesome!
> is the parallel sequential monte carlo implemented?

Thanks. I tried implementing SMC using Threads, but it seems Threads is not very stable yet. 

Ref: #65

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/26051536/cacbe0fc-39a5-11e7-92d3-896d1737d509.png)

**Comment by AIAdventures** [comment]
getting a few issues with another example

**Comment by AIAdventures** [comment]
gdemo.ipynb

**Comment by yebai** [comment]
We stoped exporting `plot` from Turing (#155). Try `Turing.plot` instead of `plot`.

**Comment by AIAdventures** [comment]
no error...but no plot either.
Is this correct?
Best,
Andrew

**Comment by yebai** [comment]
You need to save the plot as a file to view it:

```julia
p = Turing.plot(c3)
Turing.draw(p, fmt=:pdf, filename="gdemo-plot.pdf")
```

**Comment by AIAdventures** [comment]
ah ok

**Comment by AIAdventures** [comment]
cheers!
