### ISSUE TITLE
building Turing fails on MacOS (Julia Version 0.5.2)

### ISSUE THREAD

**Issue by awellis** [yebai/Turing.jl#260]
building Turing fails. I then attempted to run `Pkg.test("Turing")` and got the following error message:

[Turing]:  Observe - `x` is an observation
  in @~(::Any, ::Any) at compiler.jl:28
[Gibbs] Sampling...  0%  ETA: 0:25:45
  ϵ:  0.2
  α:  0.9994173943105447ERROR: LoadError: LoadError: error compiling forkc: error compiling copy: could not load library "libtask"
dlopen(libtask.dylib, 1): image not found
 in #resample!#27(::Bool, ::Function, ::Turing.ParticleContainer{Turing.Traces.Trace{:R}}, ::Turing.#resampleSystematic, ::Turing.Traces.Trace{:R}) at /Users/andrew/.julia/v0.5/Turing/src/core/container.jl:170
 in resample!(::Turing.ParticleContainer{Turing.Traces.Trace{:R}}, ::Function, ::Turing.Traces.Trace{:R}) at /Users/andrew/.julia/v0.5/Turing/src/core/container.jl:152
 in step(::Function, ::Turing.Sampler{Turing.PG}, ::Turing.VarInfo) at /Users/andrew/.julia/v0.5/Turing/src/samplers/pgibbs.jl:70
 in step(::Function, ::Turing.Sampler{Turing.PG}, ::Turing.VarInfo, ::Bool) at /Users/andrew/.julia/v0.5/Turing/src/samplers/pgibbs.jl:48
 in sample(::#gdemo2_model_##282, ::Turing.Gibbs) at /Users/andrew/.julia/v0.5/Turing/src/samplers/gibbs.jl:84
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at /Users/andrew/.julia/v0.5/Turing/test/runtests.jl:83 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/andrew/.julia/v0.5/Turing/test/compiler.jl/sample.jl, in expression starting on line 18
while loading /Users/andrew/.julia/v0.5/Turing/test/runtests.jl, in expression starting on line 71
=========================================[ ERROR: Turing ]==========================================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/andrew/.julia/v0.5/Turing/test/runtests.jl`, ProcessExited(1)) [1]

====================================================================================================
INFO: No packages to install, update or remove
ERROR: Turing had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:748
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258

What is libtask?

this is the output of versioninfo():
Julia Version 0.5.2
Commit f4c6c9d4bb (2017-05-06 16:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

**Comment by yebai** [comment]
Hi can you post the error message for running Pkg.build("Turing").

**Comment by awellis** [comment]
sure, here it is:

julia> Pkg.build("Turing")
INFO: Building Homebrew
Updated 1 tap (homebrew/core).
==> Updated Formulae
minicom
INFO: Building Cairo
WARNING: BinDeps.shlib_ext is deprecated.
  likely near /Users/andrew/.julia/v0.5/Cairo/deps/build.jl:112
INFO: Building Rmath
INFO: Building Turing
gcc -DJULIA_ENABLE_THREADING=1 -fPIC -DJULIA_INIT_DIR=\"/Applications/Julia-0.5.app/Contents/Resources/julia/lib\" -I/Applications/Julia-0.5.app/Contents/Resources/julia/include/julia  -O2 -shared -fPIC task.c -L/Applications/Julia-0.5.app/Contents/Resources/julia/lib -Wl,-rpath,/Applications/Julia-0.5.app/Contents/Resources/julia/lib -ljulia -o libtask.dylib
In file included from task.c:6:0:
/Applications/Julia-0.5.app/Contents/Resources/julia/include/julia/julia.h: In function ‘jl_eh_restore_state’:
/Applications/Julia-0.5.app/Contents/Resources/julia/include/julia/julia.h:1513:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t i = locks->len;i > eh->locks_len;i--)
         ^
/Applications/Julia-0.5.app/Contents/Resources/julia/include/julia/julia.h:1513:9: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [task] Error 1
=========================================[ ERROR: Turing ]==========================================

LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
while loading /Users/andrew/.julia/v0.5/Turing/deps/build.jl, in expression starting on line 1

====================================================================================================

==========================================[ BUILD ERRORS ]==========================================

WARNING: Turing had build errors.

 - packages with build errors remain installed in /Users/andrew/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Turing")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================

**Comment by yebai** [comment]
The makefile has been improved, try re-build by running

Pkg.checkout("Turing", "master");
Pkg.build("Turing");

**Comment by awellis** [comment]
thanks, that works
