### ISSUE TITLE
Fix warning for re-defining model

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#264]
The current `@model` implementation will generate warning messages overtime when a model function is called (e.g. `gdemo(y)`). This is a bit annoying since we frequently make use of the syntax

```julia
sample (gdemo(y), engine)
```

**Comment by xukai92** [comment]
Is it possible to add cache for `gdemo()` so that it will cache the generated function by `hash(y) => modelf`

**Comment by yebai** [comment]
Yes, it is feasible. I'll give it a try.

**Comment by yebai** [comment]
Fixed by #322
