### ISSUE TITLE
Split NUTS warmup into several windows

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#265]

**Comment by xukai92** [comment]
How should we deal with the maximum number of iterations set by the user then? Shrink the windows or cut it?

**Comment by yebai** [comment]
Shall we assume the minimal number of samples per chain for NUTS is 2k, similar to Stan? Then always use the first 1k to warmup.

**Comment by xukai92** [comment]
Yes we can. Then in this case do we want to disable the interface of setting adaption number in sampler algorithm?

**Comment by yebai** [comment]
For debugging purposes, let's keep it but throw a warning when it is mis-specified.

**Comment by xukai92** [comment]
Closed by #273
