### ISSUE TITLE
Automating benchmark summary

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#274]
Automatically merging benchmark summaries into a single file to view.

**Comment by xukai92** [comment]
Package for sending JSON from Julia: https://github.com/JuliaWeb/Requests.jl

**Comment by yebai** [comment]
This looks cool!

**Comment by yebai** [comment]
Note we have a project website on the departmental server

http://turing.eng.cam.ac.uk/

we can make this of this to slowly build a website.

**Comment by xukai92** [comment]
How can I get access to the sever of this website?

**Comment by yebai** [comment]
I've emailed CUED computer officers. Let's see what they can offer!

**Comment by xukai92** [comment]
Cool. It will be good if we can build upon it directly.

**Comment by xukai92** [comment]
@yebai Maybe we can use the GitHub Page (https://pages.github.com/) to host the homepage of the website. Can you try to create one for the Turing repo?

**Comment by yebai** [comment]
Done! See 
http://yebai.github.io/Turing.jl/

**Comment by xukai92** [comment]
Great!

**Comment by xukai92** [comment]
We now have a simple homepage at http://yebai.github.io/Turing.jl/ and a log repository at http://80.85.86.210:1111/. Shall we close this issue now?

**Comment by yebai** [comment]
Yes we can probably close this issue now.
