### ISSUE TITLE
Notebooks using codes from the development branch

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#28]
Hi @yebai , our notebooks actually uses the development version of Turing. Do you think we need to add codes to switch from master to development in the `01-Introduction.ipynb`?

**Comment by yebai** [comment]
Sounds like a good idea! Can you modify `01-Introduction.ipynb` to reflect this?

**Comment by xukai92** [comment]
I will do it tonight.

**Comment by xukai92** [comment]
I also add instructions to do the building and testing.
