### ISSUE TITLE
Merge doc, website, and benchmark log page

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#286]
we have 3 different web pages for Turing now,

-  http://yebai.github.io/Turing.jl/ 
- and a log repository at http://80.85.86.210:1111
- and http://turingjl.readthedocs.io/

we might want to merge these pages at some time.

**Comment by xukai92** [comment]
I'm thinking of making use of GitHub's wiki, for tutorials and stuff; and leave doc only for automatic generated APIs. Otherwise updating doc is a bit tedious. How do you think?

**Comment by xukai92** [comment]
I found that it is still bit difficult to track the performance history - we need to click each file. Maybe consider automatic generate a plot or something.

**Comment by yebai** [comment]
Yes, perhaps we maintain a plot of running time(s), and add a new point to the plot every time when we push a commit. This requires us to send back benchmarking results in a organised format, then a small script on the server can extract these running times and update the plot

**Comment by xukai92** [comment]
Another tricky thing about running time is that the CI severs do not always use the same computational power to run the tests - thus only the time ratio of Turing.jl and Stan is meaningful to plot. But also, single run is quite noisy, especially the running time of Turing.jl has relative large variance.

**Comment by xukai92** [comment]
Can we move the tutorial in README.md to the wiki page, where is more easy to make changes and add contents (no commits needed), and just leave a link to this in README.md?

**Comment by yebai** [comment]
> Can we move the tutorial in README.md to the wiki page, where is more easy to make changes and add contents (no commits needed), and just leave a link to this in README.md?

YES, that makes sense!

**Comment by xukai92** [comment]
I've moved the get started part to wiki.

**Comment by xukai92** [comment]
I think we can just keep wiki for tutorials and doc for auto-gen APIs?

**Comment by xukai92** [comment]
Doc is now immigrated to wiki
