### ISSUE TITLE
Make better use of view

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#288]
`arr[2:3]` actually makes a copy of subset of array but `view(arr, 2:3)` refer to the same memory. This is clear in the current `VarInfo` - should make sure it is leveraged.

**Comment by xukai92** [comment]
Actually the use of `view` doesn't help speed-up things a lot because in HMC we need to make copy of `θ` in each leapfrog step. Even with use of `view`, we still need to make manual `copy`. But this does help make the use of `copy` much more clear. And we should always assume the indexing of `VarInfo` is just a view.

**Comment by yebai** [comment]
closed in favour of #305
