### ISSUE TITLE
Plan for adding comments

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#29]
We really need better comment practice for our source code. I guess we can start to improve it by assigning those source code to who wrote it.
## Note on how to comment

Using `"""` to add comments before functions so that they can be captured by `Base.Docs.binding` (more practice see [documentation](http://docs.julialang.org/en/release-0.5/manual/documentation/))

This style of documentation can be also easily toggled in Juno/Atom, which would potentially help future development a lot.

We may also refer to other good open source projects, e.g. [normal.jl](https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/normal.jl), in which the comments contains three parts 1) description 2) example code 3) external link.
## Progress

Please tick once the file is well commented (file list is from the development branch).

`/`
- [x] `Turing.jl`

`core/`
- [x] `compiler.jl`
- [x] `io.jl`

`samplers/`
- [x] `hmc.jl`
- [x] `is.jl`
- [x] `pgibbs.jl`
- [x] `smc.jl`

`trace/`
- [x] `tarray.jl`

**Comment by yebai** [comment]
Thanks for the suggestions. I agree that we should gradually add comments to previous code and keep this issue updated. @adscib @xukai92 @matejbalog

**Comment by xukai92** [comment]
I've done one for my `replay.jl`. Please check the file [replay.jl](https://github.com/yebai/Turing.jl/blob/development/src/samplers/support/replay.jl) as a reference of comments binding. 

And any suggestions on the comments style is welcome!

**Comment by yebai** [comment]
Docs building is currently broken for the development branch. 

BTW, did you remove all previous docs? I think we might still need to keep them. Ideally we should write all docs with docstring, but this might be hard in some cases, e.g. documentation that does not belong to any source file.
