### ISSUE TITLE
Make Turing.jl 0.6 compatible

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#293]
Typing system is kind of changed - would need some refactors.

Related issue: https://github.com/yebai/Turing.jl/issues/173

I would suggest that we fix https://github.com/yebai/Turing.jl/issues/177 and also put 0.6 support in our 0.3 release?

**Comment by yebai** [comment]
@ChrisRackauckas This is already planed in 0.3.1, which we plan to fix the adaption issue (#324) and Julia 0.6 compatibility.

**Comment by emilemathieu** [comment]
Closed the duplicate issue https://github.com/yebai/Turing.jl/issues/330

**Comment by yebai** [comment]
cc @xukai92 @emilemathieu @ae-foster @ChrisRackauckas 

We have fixed all known compatibility issues of Turing with Julia 0.6. The master branch of Turing now supports (requires) Julia 0.6.

**Comment by ChrisRackauckas** [comment]
Great thanks! When do you plan on tagging?

**Comment by yebai** [comment]
There are some remaining issues with the NUTS sampler, mostly related to robust adaption (see https://github.com/yebai/Turing.jl/milestone/5). I planned to fix those issues altogether in 0.3.1. But perhaps we can move these issues to 0.3.2 and make a new tagging now. What do you think?

**Comment by ChrisRackauckas** [comment]
I would prefer a quicker tag, and more can always be added later of course. Reviewing tags in METADATA is easier when you have less per tag.

**Comment by yebai** [comment]
I see - will do.

**Comment by emilemathieu** [comment]
I have weird errors now:
>LoadError: MethodError: no method matching ##mhtest_model#687()
The applicable method may be too new: running in world age 23509, while current world is 23513.

@yebai Would you have any idea of where that could come from ?

**Comment by mkborregaard** [comment]
Would it maybe be an idea to add 0.6 to the travis tracker on the readme.md now this works?

**Comment by xukai92** [comment]
I've added the badge of 0.6 though I think the compilation doesn't pass because of the Stan dependency. For this reason I added a **News** sections explicitly saying that Turing.jl is 0.6 compatible.
