### ISSUE TITLE
Move notebooks

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#296]
we have BayesNN demo back now, the only notebooks we want to move back  (#238) are

- https://github.com/yebai/Turing.jl/blob/master/doc/source/notebooks/04-Bench-Scalability.jl.ipynb
  - Do we still want this, considering we have a HMM one already and have a lot of benchmark models on testing scability
- https://github.com/yebai/Turing.jl/blob/master/doc/source/notebooks/05-Ornstein-Uhlenbeck.ipynb
- https://github.com/yebai/Turing.jl/blob/master/doc/source/notebooks/06-Demo-CRP.ipynb

**Comment by xukai92** [comment]
Closed by https://github.com/yebai/Turing.jl/pull/321
