### ISSUE TITLE
Improving the HMC sampler

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#30]
~~Here is my plan for the improvement of the HMC sampler (with priorities from high to low)~~

Progress:

- [x] Replace `dDistribution` with `Distribution`
~~- [ ] Replay detection for each prior variable~~
~~- [ ] Implement NUTS~~
~~- [ ] Implement the reverse mode of AD~~
- [x] Separate gradient computation from the actual HMC sampler. This makes it easier to use gradients for other purposes, e.g. sharing code between HMC and NUTS.
- [x] Support [matrix type](http://distributionsjl.readthedocs.io/en/latest/matrix.html) random variables
~~- [ ] Prepare HMC sampler for compositional inference interface, see #55~~
- [x] Support variables with constrained support (e.g. the Beta distribution). 

~~I've already looked into how to do the first one. I've check the `Distribution` package and see most of the distributions are supporting `Dual` now, expect some Kolmogorov-related distributions which I'm not even familiar with. I believe this one can be done soon.~~

**Comment by xukai92** [comment]
Another question about the HMC is: shall we keep both normal HMC and NUTS in the same time?

By the way, the new [MHMC](http://arxiv.org/pdf/1607.02738v1.pdf) also looks cool. Maybe we can also implement it.

**Comment by yebai** [comment]
>Another question about the HMC is: shall we keep both normal HMC and NUTS in the same time?

@xukai92 Let's keep HMC and NUTS separate for now.  

>By the way, the new MHMC also looks cool. Maybe we can also implement it.

Agreed : ) 
cc'ing @nileshtrip

**Comment by yebai** [comment]
> I've already looked into how to do the first one. I've check the Distribution package and see most of the distributions are supporting Dual now, expect some Kolmogorov-related distributions which I'm not even familiar with. I believe this one can be done soon.

Let's first re-implement AD without `dDistribution` within the next 1-2 weeks.

**Comment by xukai92** [comment]
@yebai I was working on it yesterday. Basically the replacement of `dDistribution` with `Distribution` was a very quick fix but there still so potential problems with the `Distribution` package.

Although all the distributions support `Dual` as parameter types now, some of them (like `Beta`) are dependent on external packages which only supports `Float64` (see this [issue](https://github.com/JuliaStats/Distributions.jl/issues/541#issuecomment-249209397)).

**Comment by yebai** [comment]
Thanks for the info - I will have a look at these tonight.

**Comment by xukai92** [comment]
Hi Hong, just done the re-write for Beta and Gamma and it works fine in my local dirty `StatsFuns.jl`. But I don't know how to overload them *within* `Distributions.jl` - it seems that simply reloading them in `Turing.jl` will not make `Distributions.jl` use the new definitions. Any idea?

**Comment by xukai92** [comment]
My fork of `StatsFuns.jl`: https://github.com/xukai92/StatsFuns.jl

**Comment by xukai92** [comment]
Hi Hong I just pushed my new version which removes `dD` dependency with some new tests. I'm gonna clean up & add new test files this afternoon.

**Comment by xukai92** [comment]
@yebai I managed to resolve the overload issue of `StatsFuns.jl` within `Turing.jl` so that you don't have to use my fork of `StatsFuns.jl` to run HMC now.

**Comment by yebai** [comment]
Further improvements 

- Separate gradient computation from the HMC sampler. This makes it easier to use gradients for other purposes, e.g. sharing code between HMC and NUTS.

Some missing features of the HMC sampler:

- Support [matrix type](http://distributionsjl.readthedocs.io/en/latest/matrix.html) random variables
- Prepare HMC sampler for compositional inference interface, see #55 

- Support variables with constrained support (e.g. the Beta distribution).

**Comment by xukai92** [comment]
@yebai I edited your comments into a checkbox format so we can check the progress easily.

**Comment by xukai92** [comment]
@yebai Regarding the matrix support, after running the HMC sampler for this model (below) for a few iterations, I get an error like this.

```julia
ArgumentError("matrix is not symmetric/Hermitian. This error can be avoided by calling cholfact(Hermitian(A)) which will ignore either the upper or lower triangle of the matrix.")
```

I feel it's not an error of my implementation of matrix support. I wonder maybe I need to do some tricks to ensure the symmetric nature of the matrix to use HMC for this distribution?

Model:

```julia
using Distributions
using Turing

@model hmcmatrixsup begin
  @assume p ~ Wishart(7, [1 0.5; 0.5 1])
  @predict p
end

sample(hmcmatrixsup, HMC(10, 0.1, 3))
```

**Comment by yebai** [comment]
We need to solve the constrained variable issue in order to make this example work. 
This is because the Wishart distribution has a constrained support, proposals from an HMC sampler can violate such constraints, e.g. propose `p` that has zero probability.

A possible way to make your test pass is to overload the `logpdf` function of Wishart, and return zero for variables that is off support. We can remove this hack when constrained variable feature is implemented.

**Comment by xukai92** [comment]
I see. Will try it tonight.

**Comment by xukai92** [comment]
@yebai Can you point me to the Stan paper where gives details on how to deal with constrained variables?

**Comment by yebai** [comment]
It is part of Stan's [documentation](https://github.com/stan-dev/stan/releases/download/v2.12.0/stan-reference-2.12.0.pdf) (chap 58).

**Comment by xukai92** [comment]
Many thx!!

**Comment by xukai92** [comment]
I implemented more distributions I can do in `StatsFuns.jl` this afternoon. For now, all, other than discrete ones and noncentral ones, are done.

I guess we can't do more for `StatsFuns.jl` for now so wait for the PR (https://github.com/JuliaStats/StatsFuns.jl/pull/21) to be accepted.

**Comment by xukai92** [comment]
Some concerns about constrained support:

1. I feel that we don't actually need density transformation because all we need is an valid leap-frog step in HMC - so I just 1) transform variable from X to R, 2) move in R, 3) transform from R back to X. I think this is still correct. How do you think?
2. When constrained variable and unconstrained variables are in the same model. I found that the accept rate will be very low because the step size cannot be good for both. I think we need some trick to solve this issue. Maybe we can also do some transform on step size as well?

**Comment by yebai** [comment]
> I feel that we don't actually need density transformation because all we need is an valid leap-frog step in HMC - so I just 1) transform variable from X to R, 2) move in R, 3) transform from R back to X. I think this is still correct. How do you think?

We do need these transformed densities. Simply transform X to R before the hamiltonian integration steps and transform R' back to X' won't produce correct samples. This is because the transform is non-linear, thus the hamiltonian energy needs to be corrected by the Jacobian matrix in order to compute MH accept ratio correctly. A possible good reference is Radform Neal's [HMC review paper](https://arxiv.org/pdf/1206.1901.pdf) (see Sec 2.2).

The theory might be a bit complex to understand. However the basic idea should be quite simple: we need to use `logpdf` or `logpdf_transform` consistently in a sampling method. We only convert the simulated value back to the original space when the sampling is completed. For instance, if we run HMC on the transformed space, then all the gradients and MH accept ratio needs to be computed using the transformed joint density `logpdf_transform`. When we finish one HMC step, we call the `invlink` function to convert the simulated sample back to the original space.

**Comment by yebai** [comment]
Seems we can close this issue now?

**Comment by xukai92** [comment]
Yes! Let me close it.
