### ISSUE TITLE
Fix Appveyor

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#302]
All tests in the recent Appveyor build (https://ci.appveyor.com/project/yebai/turing-jl/branch/master/job/3a3kfg647wyipjiu) pass but Appveyor still gave us error?

**Comment by yebai** [comment]
Hopefully this is fixed now on the master branch.

**Comment by yebai** [comment]
AppVeyor is running now, but there are some failed tests.

**Comment by xukai92** [comment]
Seems they are not Turing.jl errors. Win32 simply failed to install Cairo.jl

**Comment by yebai** [comment]
I checked the Cairo package; seems their tests on Win32 fails too, so it's not a Turing issue.
