### ISSUE TITLE
Try out memory pre-allocation

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#305]
Currently Turing allocates parameter memory every time the program is re-executed, which is wasteful and potentially a major bottleneck for performance.  Perhaps we should start by verifying whether pre-allocating parameters memory will improve performance? We could start with 

- LDA
- MoC

etc..

**Comment by xukai92** [comment]
Experiment results

Model | Global | Normal | Dim
------------ | -------------| ------------- | ---
MoC | 16.13 | 16.31 | 
LDA | 25.82 | 27.68 | 

Time here are averages of 5 runs.

Code used for "global" are pasted below:
**MoC**
```julia
@model nbmodel(K, V, M, N, z, w, doc, alpha, beta) = begin
  theta ~ Dirichlet(alpha)
  phi = Array{Any}(K)
  for k = 1:K
    phi[k] ~ Dirichlet(beta)
  end

  log_theta = log(theta)
  Turing.acclogp!(vi, sum(log_theta[z]))

  log_phi = map(x->log(x), phi)
  lp = mapreduce(n->log_phi[z[doc[n]]][w[n]], +, 1:N)
  Turing.acclogp!(vi, lp)

  phi
end
```
:vs:
```julia
theta = Vector{Real}(4)
phi = Vector{Vector{Real}}(4)
for k = 1:4
  phi[k] = Vector{Real}(10)
end
log_theta = Vector{Real}(4)
log_phi = Vector{Real}(4)

@model nbmodel(K, V, M, N, z, w, doc, alpha, beta) = begin
  theta ~ Dirichlet(alpha)
  # phi = Array{Any}(K)
  for k = 1:K
    phi[k] ~ Dirichlet(beta)
  end

  log_theta = log(theta)
  Turing.acclogp!(vi, sum(log_theta[z]))

  log_phi = map(x->log(x), phi)
  lp = mapreduce(n->log_phi[z[doc[n]]][w[n]], +, 1:N)
  Turing.acclogp!(vi, lp)

  phi
end
```

**LDA**
```julia
@model ldamodel_vec(K, V, M, N, w, doc, beta, alpha) = begin
  theta = Matrix{Real}(K, M)
  theta ~ [Dirichlet(alpha)]

  phi = Matrix{Real}(V, K)
  phi ~ [Dirichlet(beta)]

  phi_dot_theta = log(phi * theta)

  lp = mapreduce(n->phi_dot_theta[w[n], doc[n]], +, 1:N)
  Turing.acclogp!(vi, lp)
end
```
:vs:
```julia
global theta = Matrix{Real}(2, 25)
global phi = Matrix{Real}(5, 2)

@model ldamodel_vec(K, V, M, N, w, doc, beta, alpha) = begin
  global theta, phi

  # theta = Matrix{Real}(K, M)
  theta ~ [Dirichlet(alpha)]

  # phi = Matrix{Real}(V, K)
  phi ~ [Dirichlet(beta)]

  phi_dot_theta = log(phi * theta)

  lp = mapreduce(n->phi_dot_theta[w[n], doc[n]], +, 1:N)
  Turing.acclogp!(vi, lp)
end
```

For LDA, I cannot run inference without using global, which I believe is related to our vectorisation implementation (?)

**Comment by yebai** [comment]
Are these experiments using the same setting as #275?

**Comment by xukai92** [comment]
I used `HMC(2000, 0.01, 5)` for **both** LDA and MoC this time.
- For LDA before we used `HMC(2000, 0.025, 10)`.
- For MoC before we used `HMC(2000, 0.01, 5)` as well.

**Comment by yebai** [comment]
There is only some small improvements here (25.8 vs 26.7), with roughly 1sec speedup. However, even with parameters pre-allocated, Turing still internally causes many  memory allocations, e.g. the following line

https://github.com/yebai/Turing.jl/blob/master/src/samplers/hmc.jl#L167

will basically void the effort of pre-allocating parameters.

**Comment by xukai92** [comment]
Yes I see that as well. Internally Turing.jl still re-allocs them; I guess we need to do something like https://github.com/yebai/Turing.jl/blob/master/src/samplers/hmc.jl#L173, for both vec and not-vec `assume()` - so that at least `assume()` doesn't re-alloc them?

**Comment by xukai92** [comment]
By https://github.com/yebai/Turing.jl/blob/master/src/samplers/hmc.jl#L173 I mean take the variable in the program scope as a parameter of `assume()`

**Comment by yebai** [comment]
Yes, we can do that. But there are still many other places calling `getindex(vi, idx)`, e.g. inside `leapfrog` function, inside `gradient` function, etc.. And for every call to `getindex`, we will waste 1sec roughly..

**Comment by yebai** [comment]
Ps. It is better to produce these running time numbers automatically on Travis, as what we do in #275

**Comment by xukai92** [comment]
I think it is possible to do everything in-place but we need to think about it carefully. 

Also for not-vec assume, I guess we can't simply support user to use pre-defined variables in our current syntax: we assume left hand side is not defined for `left ~ right`.

Can we have a meeting on these points tomorrow?

**Comment by yebai** [comment]
@xukai92 I can't do tomorrow, but Wednesday works fine.

**Comment by xukai92** [comment]
@yebai Let's meet up on Wednesday then!

**Comment by yebai** [comment]
After some discussions, we've come up with some potential bottlenecks involving redundant memory allocations:

- `getindex(VarInfo, idx)` currently creates a copy of memory indexed by `idx`. Maybe a better implementation is  to use ArrayView?
- `acclop!`: when called inside a for loop, this function could be slow.

**Comment by ChrisRackauckas** [comment]
>getindex(VarInfo, idx) currently creates a copy of memory indexed by idx. Maybe a better implementation is to use ArrayView?

You can just use `@view` instead. Sometimes views get allocated to the stack, but that's something which will be fixed in a Julia 1.x as a compiler optimization, so I would highly recommend just using the Base views.

**Comment by xukai92** [comment]
Cool - thanks for this suggestion!

**Comment by yebai** [comment]
shall we fix this before releasing 0.3?

**Comment by xukai92** [comment]
What's left to do? I believe we later came to a conclusion that the memory allocation (without initialisation) is cheap.

**Comment by yebai** [comment]
>>getindex(VarInfo, idx) currently creates a copy of memory indexed by idx. Maybe a better implementation is to use ArrayView?

>You can just use @view instead. Sometimes views get allocated to the stack, but that's something which will be fixed in a Julia 1.x as a compiler optimization, so I would highly recommend just using the Base views.

Has this already been resolved?

**Comment by xukai92** [comment]
Yes (and no) - I actually didn't use `ArrayView` in the end but use `view(arr, idx)`, which is the equivalent to `@view` I believe.

**Comment by yebai** [comment]
I see, let's close this issue then

**Comment by xukai92** [comment]
Sure
