### ISSUE TITLE
Why no need of using Distributions now?

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#307]
I found that we no longer need to call `using Distributions` to run inference. Why?

**Comment by yebai** [comment]
Not entirely sure, but one possible reason is that the model function is now generated in the Turing package scope, which already imports the Distributions.

**Comment by xukai92** [comment]
I guess so. I think it's fine if that's the case.

**Comment by xukai92** [comment]
I found that after `using Turing` I can use things like `Normal` even outside `@model`

**Comment by yebai** [comment]
This is also true for the Mamba package.

**Comment by xukai92** [comment]
I see. I am just bit worried if it is a good Julia practice. Maybe we can ignore it for now.
