### ISSUE TITLE
VarName is slow

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#308]
The current variable naming mechanism inserts code to generated model function, which seems to cause a (substantial) performance issue.

**Comment by xukai92** [comment]
Quick experiment of generate 1,000 `VarName`:

```
1st Run: 
Kai : 0.852095485
Hong: 0.480163797
2nd Run: 
Kai : 0.705414626
Hong: 0.007186917
```

Your implementation is not only fast but also cached by Julia somehow?

Code is in the end of `benchmark/optimization.jl` (https://github.com/yebai/Turing.jl/pull/310).

**Comment by xukai92** [comment]
I'm going to make Turing.jl use your implementation today.

**Comment by xukai92** [comment]
https://github.com/yebai/Turing.jl/pull/310/commits/f8200df1cd84de0a4fa5869285bfab610fb7b587 and https://github.com/yebai/Turing.jl/pull/310/commits/3b9f5f6d4201a8f9924b9f3608e5a66897750f1d removes the use of `varname`

**Comment by xukai92** [comment]
Note:

`@VarName` has to be inserted to the generated function directly because it cotains runtime information. As there is a place where the compile time symbol is needed, I added a function `getvsym` for that purpose. By these two changes, `varname()` is removed.

**Comment by xukai92** [comment]
@yebai The change doesn't seem to have obvious improvement. Worsely, the benchmark of `~` in `optimization.txt` even becomes slower. Any idea?

**Comment by xukai92** [comment]
Another run without any changes to source codes (e8e35aab6f14712bad8c904b9ee83d51bed42778) seemed to be better.

**Comment by yebai** [comment]
> @yebai The change doesn't seem to have obvious improvement. Worsely, the benchmark of ~ in optimization.txt even becomes slower. Any idea?

Can you point me to the corresponding result file?

**Comment by yebai** [comment]
perhaps we can close this issue now?

**Comment by xukai92** [comment]
Yes.
