### ISSUE TITLE
Make `resample!` work with ProgressMeter

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#317]
#171

**Comment by yebai** [comment]
Update: `BayesHMM` now runs fine with Atom, but still (mysteriously) broken on Jupyter notebook.

**Comment by yebai** [comment]
Update 2: this should be working for both Atom and Jupyter notebook now. The bug comes from two sources

- Julia makes some updates to gc mechanism, see [link](https://github.com/JuliaLang/julia/pull/17116)
- There is a missing exception handler in task.c

**Comment by xukai92** [comment]
closed by #319
