### ISSUE TITLE
Merge readthedoc website into wiki

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#320]
- Copy everything from Turing's readthedoc website to wiki
- Disable/delete read the Turing's readthedoc website.

**Comment by xukai92** [comment]
Closed by https://github.com/yebai/Turing.jl/pull/321 (remove doc folder) and https://github.com/yebai/Turing.jl/commit/d4707f342c644028781d4daa216aa63f04a83643 (remove doc badge)

**Comment by yebai** [comment]
@xukai92  Could we also disable/delete the website - http://turingjl.readthedocs.io/
