### ISSUE TITLE
Sampling interface update

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#326]
How should we re-design our sampling interface so that it can be consistent to Stan's type (Stan.hmc, Stan.adapt)

**Comment by xukai92** [comment]
This should be done before https://github.com/yebai/Turing.jl/issues/324

**Comment by xukai92** [comment]
Considering backward-compatibility and the purpose of fixing #324, for now, it's better & easier to provide another interface using `Stan.hmc` and `Stan.adapt` to call `Turing.jl`'s interface first. 

We can just ignore some setting which unavailable in `Turing.jl` for now, and fix then later when we update internals. Do you think it's fine?

**Comment by yebai** [comment]
> We can just ignore some setting which unavailable in Turing.jl for now, and fix then later when we update internals. Do you think it's fine?

Sounds good to me!

**Comment by xukai92** [comment]
This is done in https://github.com/yebai/Turing.jl/pull/343

**Comment by xukai92** [comment]
Closed by #343
