### ISSUE TITLE
Demo-CRP notebook

### ISSUE THREAD

**Issue by emilemathieu** [yebai/Turing.jl#328]
Hi all !

I am interested in the DP mixture, thus I've had a look at the `06-Demo-CRP.ipynb` file, but the interesting parts; `IArray`, `PolyaUrn` and `randclass` are not defined. Is it intended ?

Moreover, the syntax is weird, should not it be ?
```julia
data = [1.0, 1.1, 1.2, -10, -15, -20, 0.01, 0.1, 0.05, 0]
N    = length(data)

@model dpmixa(x) = begin
  ϕ ~ IArray(Normal(0, 10)) # Infinite Array

  urn = PolyaUrn(1.72)
  μ, classes = tzeros(N), tzeros(Int, N)
  for i in 1:N
    classes[i]  = randclass(urn)
    μ[i]  = ϕ[classes[i]]
    x[i] ~ Normal(μ[i], 1)
  end
  K = length(unique(classes))

  return K, μ
end

resulta  = sample(dpmixa(data), PG(20, 50))
```

Thanks

**Comment by yebai** [comment]
Hi @emilemathieu, these functions exist in earlier private versions of Turing. I'll try to find them and make them part of the public repo this week.

**Comment by emilemathieu** [comment]
Thanks @yebai !

**Comment by emilemathieu** [comment]
@yebai any news on this ?

**Comment by emilemathieu** [comment]
Hello all !
I've been trying to implement a Dirichlet Process mixture model, and sampling from it, but I have some issues only related to the mixture model.
The `for-loop` apparently stops after the first iteration, `"end loop"` is never printed; this may come from the way the model is compiled. Do you have any idea why ?

```julia
using Turing, Distributions

data = [1.0, 1.1, 1.2, -10, -15, -20, 0.01, 0.1, 0.05, 0]

@model dpmixa(x) = begin
  N = length(x)
  println(N)
  # μ ~ DP(10.0, Normal(0, 10), N) # Dirichlet Process
  μ ~ MvNormal(0 * ones(N), 10 * ones(N))

  for i in 1:N
    println(i)
    x[i] ~ Normal(μ[i], 1)
    println("end loop")
  end
  println(μ)
  K = length(unique(μ))

  return K, μ
end

sample(dpmixa(data), PG(20, 50))
```

**Comment by yebai** [comment]
Hi @emilemathieu sorry for the delay. I was on travel in the past few days. 

The program runs fine on my computer, and the following output is printed. Are you on the master branch?

```julia
Turing]:  Assume - `μ` is a parameter
  in @~(::Any, ::Any) at compiler.jl:76
[Turing]:  Observe - `x` is an observation
  in @~(::Any, ::Any) at compiler.jl:57
10
1
end loop
2
end loop
3
end loop
4
end loop
5
end loop
6
end loop
7
end loop
8
end loop
9
end loop
10
end loop
[-10.4515,17.9684,13.2468,7.52923,-7.15283,2.90442,-6.71127,-3.40602,-12.7698,11.9914]
/=======================================================================
| VarInfo
|-----------------------------------------------------------------------
| Varnames  :   ["{dpmixa_var84,μ}:1"]
| Range     :   UnitRange{Int64}[1:10]
| Vals      :   Array{Real,1}[Real[-10.4515,17.9684,13.2468,7.52923,-7.15283,2.90442,-6.71127,-3.40602,-12.7698,11.9914]]
| GIDs      :   [0]
| Trans?    :   Array{Bool,1}[Bool[false]]
| Logp      :   Real[-956.78]
| Index     :   0
| #produce  :   0
\=======================================================================
```

**Comment by yebai** [comment]
PS. You can simulating the model from prior by using the following syntax

```julia
f = dpmixa(data);
f(); # calling model function directly will simulate from the model prior
```

We have found this very helpful debugging / inspecting models in the past.

BTW, I saw that you have a `DP` distribution in your model, did you implement this distribution?

**Comment by yebai** [comment]
> I was wondering, why is Distributions.logpdf{T<:Real}(d::DP, x::Vector{T}) needed when sampling from the prior (f = dpmixa(data); f()) but not when sampling from the posterior (sample(dpmixa(data), PG(50, 200))) ?

When sampling from the prior, the compiled model function will also try to compute the joint probability of the sample under the prior distribution. This became helpful when implementing samplers, since the accept ratio can be easily derived from the `VarInfo` data structure. It should be Ok to implement a NULL function first for DP.

**Comment by emilemathieu** [comment]
Thanks for your clear answer @yebai !

Would you like me to create a PR with my *Dirichlet Process* distribution (which is now different from the code above) along with an example of a *DP* used as a prior for a gaussian mixture model ?

**Comment by yebai** [comment]
> Would you like me to create a PR with my Dirichlet Process distribution (which is now different from the code above) along with an example of a DP used as a prior for a gaussian mixture model ?

Yes, please!
