### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#33]
Out test coverage is 68% for the development branch at this issues is post, and I am aiming to improve it to over 90%. There are fews things need to be known for all.

- [x] Test coverage reaches 90%

**Keep `runtest.jl` structured**

Please check the new `runtest.jl` file. When adding new tests in the future, keep it structured using the current way so that we can tell which source file we are testing for each test case.

**Review of old test cases**

I noticed some comments in them are out-of-date. @yebai Can you also have a check and remove unnecessary ones.

**Add new tests**

Clearly there are some source files not having specific test files. I guess we can add more along with adding more commands ( #29 ), which is not actively in process.

**Comment by xukai92** [comment]
I looked into the detail of test coverage and wonder if those functions that haven't been used are just abandoned.

**Comment by yebai** [comment]
I can't remember what functions are not used; can we remove obviously obsolete functions, but keep potentially useful functions somewhere separately (ie. not affecting test coverage).

**Comment by yebai** [comment]
>Keep runtest.jl structured
>Please check the new runtest.jl file. When adding new tests in the future, keep it structured using the current way so that we can tell which source file we are testing for each test case.

It makes a lot sense to do it this way!

>Review of old test cases
>I noticed some comments in them are out-of-date. @yebai Can you also have a check and remove unnecessary ones.

Yes, I will take a look!

**Comment by yebai** [comment]
PS. can we create a separate branch (e.g. test-coverage) and keep all work related there?

**Comment by xukai92** [comment]
> I can't remember what functions are not used; can we remove obviously obsolete functions, but keep potentially useful functions somewhere separately (ie. not affecting test coverage).

I guess we can either 

- Create a branch called old-development and come back when some functions are needed, or
- Create a folder called old-src or something in the root path of Turing

Which one do you think is better?

> PS. can we create a separate branch (e.g. test-coverage) and keep all work related there?

I wonder whether a separate branch for test coverage is a good idea as we need keep running these updated testes for our updated code.

**Comment by yebai** [comment]
> Create a branch called old-development and come back when some functions are needed
 
Let's do this.

> I wonder whether a separate branch for test coverage is a good idea as we need keep running these updated testes for our updated code.

In general we should avoid commit work in progress directly to development or master. Instead, we can keep a new branch for each new task, and create a PR towards to development/master when it is done.

**Comment by xukai92** [comment]
The coverage is 85% after removal these files.

> In general we should avoid commit work in progress directly to development or master. Instead, we can keep a new branch for each new task, and create a PR towards to development/master when it is done.

Yeah! I'll stick to this as well.

BTW, do you keep the `old-development` locally?

**Comment by xukai92** [comment]
@yebai I wonder if `src/distributions/distributions.jl` should also be removed?
