### ISSUE TITLE
Upgrade to v0.6

### ISSUE THREAD

**Issue by ChrisRackauckas** [yebai/Turing.jl#330]
Julia v0.6 is the current release. It seems there's no tests on v0.6, and when I try `using Turing` on v0.6 it stalls.

**Comment by yebai** [comment]
Yes, we plan to work on that. There is an issue prevent us from using Julia 0.6 at the moment, see

https://github.com/yebai/Turing.jl/issues/173

https://github.com/JuliaLang/METADATA.jl/pull/10646#issuecomment-321925262

**Comment by yebai** [comment]
I made some progresses on this issue. Now Turing can load within Julia 0.6, however, some tests are currently broken (`Pkg.test("Turing")`) -- the issue seems related to a change on the Julia side (https://github.com/JuliaLang/julia/issues/21356).

**Comment by kleinschmidt** [comment]
See also JuliaLang/julia#19774

**Comment by xukai92** [comment]
I found that if we do the model evaluation and calling `sample()`, Julia doesn't throw the error. E.g.

```julia
modelf = gdemo(x)
sample(modelf, alg)
```

**Comment by xukai92** [comment]
From https://docs.julialang.org/en/stable/manual/methods/#Redefining-Methods-1
> But neither you, nor any of your callers, nor the functions they call, or etc. can call this new method definition!

**Comment by emilemathieu** [comment]
Any news on this issue ?
Do we have a list of the issues/tests yet solved ?

**Comment by xukai92** [comment]
@emilemathieu Please see https://github.com/yebai/Turing.jl/pull/341

In short Turing can be used in Julia 0.6 in this PR, and we are adapting the new co-routine and fixing some minor issues.

**Comment by yebai** [comment]
@xukai92 let's try to merge the PR this week - I will make an effort of fixing coroutine issue; Could you fix other known issues?

**Comment by emilemathieu** [comment]
Duplicate: https://github.com/yebai/Turing.jl/issues/293

**Comment by yebai** [comment]
As of now, all tests in #341 are passing on Julia 0.6.

**Comment by ChrisRackauckas** [comment]
For the warnings you can just install Femtocleaner 

https://github.com/JuliaComputing/FemtoCleaner.jl
