### ISSUE TITLE
Particle Gibbs (PG)

### ISSUE THREAD

**Issue by emilemathieu** [yebai/Turing.jl#333]
Hi all !

Would you have a bit of documentation or insights about what's implemented behind [PG](https://github.com/yebai/Turing.jl/wiki/APIs#pgn_particlesint-n_itersint) ? By reading the code I understood that it looks more like a conditional SMC.

In the article [Particle Markov chain Monte Carlo methods](http://www.stats.ox.ac.uk/~doucet/andrieu_doucet_holenstein_PMCMC.pdf) section 2.4.3, `Particle Gibbs` is defined as
> a Gibbs sampler which samples iteratively from p(θ|y1:T, x1:T) and p(x1:T |y1:T, θ) [...] with a special type of *PMCMC* update called the conditional *SMC* update.

but that's not what `PG` is doing. Base on the paper, the syntax could looks like
```julia
sampler = PG(1000, SMC(1, :x), HMC(1, 0.2, 3, :θ))
```

But maybe this is what is done in Turing with:
```julia
sampler = Gibbs(1000, PG(1, :x), HMC(1, 0.2, 3, :θ))
```

Is it ? If so, `PG` could be renamed `CSMC`.

Thanks for your help

**Comment by yebai** [comment]
> Is it ? If so, PG could be renamed CSMC.

That's quite right. `PG` in Turing actually refers to `CSMC`. Gibbs is slightly more general than `PG`, since it allows combination of samples like `Gibbs(HMC, HMC)`. 

@xukai92 Do you think we can change the name of `PG` to `CSMC`? Or perhaps we can create an alias `CSMC` to `PG` to keep backward compatibility?

**Comment by xukai92** [comment]
@yebai I feel having a type alias `CSMC` for `PG` is better.

**Comment by emilemathieu** [comment]
Like this ?
```julia
typealias CSMC PG
```

**Comment by yebai** [comment]
> typealias CSMC PG

Yes, that should work.

**Comment by emilemathieu** [comment]
Ok, I'll create a PR with that line added in `src/sampler/pgibbs.jl`.
How can I modify the wiki to make that clearer for everyone ?

**Comment by yebai** [comment]
> How can I modify the wiki to make that clearer for everyone ?

I'll added you to collaborators, so you can edit the wiki.

**Comment by emilemathieu** [comment]
PR for review: https://github.com/yebai/Turing.jl/pull/342
