### ISSUE TITLE
 MethodError: no method matching ##bfit_model#734

### ISSUE THREAD

**Issue by Ayush-iitkgp** [yebai/Turing.jl#337]
I am using Turing.jl to estimate the parameters of the differential equations from [here](http://nbviewer.jupyter.org/github/xukai92/TuringDemo/blob/master/Differential%20Equation/turing-de.jl.ipynb). 
I am getting the error 

> MethodError: no method matching ##bfit_model#734(::Array{Float64,2})

on executing line `chn = sample(bfit(data), HMC(400, 0.02, 4))
`
I am on the master branch. Help please :)

**Comment by yebai** [comment]
@xukai92 Could you take a look at this issue?

**Comment by xukai92** [comment]
@Ayush-iitkgp I just re-run the notebook from the beginning to that block, which was fine to me. 

Can you double check your running environment. Mine is:

Julia 0.5.2
Turing master (36e1cf791b269973e364958bf23b0f9990a8aaae)

**Comment by ChrisRackauckas** [comment]
He most likely ran it on v0.6. Probably this then:

https://github.com/yebai/Turing.jl/issues/293

**Comment by Ayush-iitkgp** [comment]
Switching to julia 0.5 worked :)
Thanks!
