### ISSUE TITLE
[SMC] Specified resampler not used

### ISSUE THREAD

**Issue by emilemathieu** [yebai/Turing.jl#338]
Hi all !

It seems that there an issue in `samplers/smc.jl`; in
```julia
resample!(particles,use_replay=spl.alg.use_replay)
```
the SMC resampler is not used, should not it be:
```julia
resample!(particles,randcat=spl.resampler,use_replay=spl.alg.use_replay)
```
?

Best,
Emile

**Comment by xukai92** [comment]
Yes I think you are right and this should be fixed. The current code works only because we by default use `Turing.resampleSystematic` as the resampler.

**Comment by emilemathieu** [comment]
Ok, I'll do a PR to fix this.

**Comment by emilemathieu** [comment]
I think that I've also spotted another mistake in `pgibbs.jl`:
```julia
assume{T<:Union{PG,SMC}}(spl::Void, dists::Vector{T}, vn::VarName, var::Any, vi::VarInfo) =
  error("[Turing] PG and SMC doesn't support vectorizing assume statement")
```
Should not it be
```julia
assume{A<:Union{PG,SMC},D<:Distribution}(spl::Sampler{A}, dists::Vector{D}, vn::VarName, var::Any, vi::VarInfo) = 
  error("[Turing] PG and SMC doesn't support vectorizing assume statement")
```
?

**Comment by emilemathieu** [comment]
PR for review: https://github.com/yebai/Turing.jl/pull/340

**Comment by xukai92** [comment]
Yes that's a mistake! Thx for spotting it.

**Comment by emilemathieu** [comment]
Fixed in https://github.com/yebai/Turing.jl/pull/340
