### ISSUE TITLE
Build failure in Julia v0.6

### ISSUE THREAD

**Issue by juliohm** [yebai/Turing.jl#348]
```julia
gcc: error: $: No such file or directory
make: *** [Makefile:12: task] Error 1
===============================[ ERROR: Turing ]================================

LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
while loading /home/juliohm/.julia/v0.6/Turing/deps/build.jl, in expression starting on line 1

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Turing had build errors.

 - packages with build errors remain installed in /home/juliohm/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Turing")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by xukai92** [comment]
This is a known issue (https://github.com/yebai/Turing.jl/issues/330 & https://github.com/yebai/Turing.jl/issues/293) - we are currently working on making Turing.jl compatible with 0.6.

**Comment by kleinschmidt** [comment]
I don't think this is a 0.6 issue; it's a problem with the Makefile. I get the same error on 0.5. It's because there are trailing `$` at the end of a couple of lines in the Makefile: https://github.com/yebai/Turing.jl/blob/32551b91aeaa1e636482c21bb085d457533d5b35/deps/Makefile#L8-L9

**Comment by yebai** [comment]
@kleinschmidt Could you create a PR for this? Also, any idea why the code actually pass on Travis?
