### ISSUE TITLE
don't override display

### ISSUE THREAD

**Issue by stevengj** [yebai/Turing.jl#353]
It looks like you are overloading `display` in an attempt to customize output.  This is the wrong way to do it — see the manual on [custom pretty printing](https://docs.julialang.org/en/release-0.6/manual/types/#Custom-pretty-printing-1).

To customize REPL output, you should override `Base.show(io::IO, x::MyType)` and/or `Base.show(io::IO, ::MIME"text/plain", x::MyType)`, as explained in the manual.

Overriding `display` directly will break IJulia, Juno, and other environments that have a custom `display` mechanism.

**Comment by yebai** [comment]
Thanks for pointing this out - we will fix this in the next release.

**Comment by xukai92** [comment]
Closed by #394
