### ISSUE TITLE
Resampling in CSMC is not optional

### ISSUE THREAD

**Issue by twgr** [yebai/Turing.jl#357]
Hey

I noticed that adaptive resampling is currently used for CSMC.  This is not actually valid as, unlike for SMC, resampling does not maintain the target for CSMC.  As such you always have to resample for a CSMC sweep.

Cheers

Tom

**Comment by emilemathieu** [comment]
One easy way to fix that is to hardcode `resampler_threshold=1.0`and no allowing the user to choose that value.

Best,
Emile

**Comment by yebai** [comment]
Thanks - we will fix this in release 0.3.1.

**Comment by emilemathieu** [comment]
I'll soon make a PR to fix this

**Comment by emilemathieu** [comment]
I pushed a PR https://github.com/yebai/Turing.jl/pull/361
