### ISSUE TITLE
Refactoring particle filtering related data structures

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#360]
Some current code related to particle filtering is buggy (#357) and/or hard to understand (#359, #358, #356) for new developers to Turing. I propose that we take this opportunity to refactor some existing particle filtering code, particularly those in `src/traces/trace.jl` and `src/core/container.jl`. 

Please feel free to comment or add links to relevant issues.

Cc: @emilemathieu @xukai92 @twgr

**Comment by emilemathieu** [comment]
I believe `src/traces/trace.jl` definitely needs some refactoring and comments (or wiki doc).
`src/core/container.jl` might need a bit of documentation or comments but is ok for now I think.

**Comment by yebai** [comment]
- [ ] Add an additional parameter to `forkc` to only delete randomness for reference particles. https://github.com/yebai/Turing.jl/issues/358#issuecomment-343319106

**Comment by emilemathieu** [comment]
Done via PR https://github.com/yebai/Turing.jl/pull/395.
