### ISSUE TITLE
[BNP] Model & metric for test

### ISSUE THREAD

**Issue by emilemathieu** [yebai/Turing.jl#371]
We need a test so as to make sure that samples are distributed according the right distribution for the BNP project.
* One way could be a correctness test such as Geweke.
* A maybe better way, is a toy model (small mixture model ?) for which we can compute the posterior (analytically or with SMC with lots of particle)

**Comment by mlomeli1** [comment]
I agree with the idea of computing analytically the posterior probabilities for a small case by combinatorial enumeration. Then, we need to compare these probabilities to the ones obtained with the SMC output using a large number of particles to asses correctness of the algorithm. See the analytic expressions for a PY mixture model in my thesis, Section 2.7.4, page 46.

**Comment by emilemathieu** [comment]
@mlomeli1 that's seems like a good idea. If I understand correctly, the idea is to enumerate all clustering possible (for a fix -- and small -- number of observations), then for each clustering compute the posterior probability of observations conditional on that clustering, finally sum the posterior joint over all combination. Then we compare the obtain quantity which is the marginal likelihood, with the unbiased estimator returned by SMC ?

Yet, I don't understand how this method can be used to assess the validity of an other sampler than SMC.

**Comment by xukai92** [comment]
There is a sample Geweke test code here https://github.com/yebai/Turing.jl/blob/master/benchmarks/gdemo-geweke.run.jl. You can probably reuse it by changing the sampling algorithm in Line 34 and 36.

**Comment by emilemathieu** [comment]
@mlomeli1 otherwise we could use Bayes rule to compute p(Pi_n = pi | {Y_j}_{j=1,..,n}) with the analytic expression of your thesis that you referred, and then compute empirical clustering from posterior sample for a model with 4 or 5 observations (ordered Bell numbers of 13 or 75).

**Comment by mlomeli1** [comment]
Yes, @emilemathieu, that's a good plan. I think I have some code in R for the analytic expression, can translate it to Julia.
@xukai92 , Geweke's getting it right test only applies for MCMC schemes.

**Comment by emilemathieu** [comment]
@mlomeli1 I've just finished the test ! :) I've done what I proposed in my previous comment and then used a Chi-square test. It can be found here: https://github.com/yebai/Turing.jl/blob/project-bnp/test/rpm.jl/pym_posterior.jl

**Comment by mlomeli1** [comment]
Well done, @emilemathieu !

**Comment by emilemathieu** [comment]
@yebai I've previously used `x = Array{Real}(N)` for the infinite mixture model I had weird errors because some variables were not deep-copied (when particles are forked) I think.
It worked by using `tzeros`. Is that why you introduced it ?
It was a silent bug so it's pretty bad...

**Comment by yebai** [comment]
> @yebai I've previously used x = Array{Real}(N) for the infinite mixture model I had weird errors because some variables were not deep-copied (when particles are forked) I think.
It worked by using tzeros. Is that why you introduced it ?
> It was a silent bug so it's pretty bad...

yes, I created `TArray` for variables that have to be deep copied when copying particles. Sorry I didn't tell you about this earlier... I'm glad that you figured this out - perhaps we should document this on the wiki.
