### ISSUE TITLE
[CSMC] Case where random variable is unknown and belongs to a different sampler

### ISSUE THREAD

**Issue by emilemathieu** [yebai/Turing.jl#373]
Currently in `CSMC` if an `assume` statement is encountered with a random variable that doest not belongs to this `CSMC`'s space (should not be updated) we get en error. Indeed since we have the following 

```julia
assume{T<:Union{PG,SMC}}(...) = begin
... 
else # !( isempty(spl.alg.space) || vn.sym in spl.alg.space)
  vi[vn] # yields error
end
```

We can fix that by checking whether that random variable exists, and if not sample it from its prior and push it to `VarInfo` with a `gid=-1` (which will be updated once resampled from its sampler), as follows 

```julia
assume{T<:Union{PG,SMC}}(...) = begin
... 
else # !( isempty(spl.alg.space) || vn.sym in spl.alg.space)
    if haskey(vi, vn)
      vi[vn]
    else
      r = rand(dist)
      push!(vi, vn, r, dist, -1)
      r
    end
end
```

For BNP mixture models, that would allow to sample new clusters (atoms' location and weight) in the particle-based method update (`CSMC` within a `Gibbs` or `SMC` within a pseudo-marginal method).

**Comment by emilemathieu** [comment]
@yebai do you have any thought on this ?

**Comment by xukai92** [comment]
I think you fix will work. But it seems that we need a more organized way to fix this along with https://github.com/yebai/Turing.jl/issues/367?

**Comment by emilemathieu** [comment]
@xukai92 i think this is orthogonal of #367.

Will `gid=-1` be an issue ? Or maybe we could try to get the right `gid` by looking at `sub_alg`'s spaces. ?

**Comment by emilemathieu** [comment]
PR: https://github.com/yebai/Turing.jl/pull/384

**Comment by yebai** [comment]
> Or maybe we could try to get the right gid by looking at sub_alg's spaces. ?

Yes, let's do what you proposed but we need a robust mechanism for mapping model variables to samplers. Ideally, if a new variable is created, we should be able to look up its sampler immediately instead of setting `gid = -1`. I will propose a method of solving this problem in #367.

**Comment by emilemathieu** [comment]
Should we close this issue ? Or should we first have a more robust way than setting `gid = -1` ?

**Comment by yebai** [comment]
I've moved the leftover issue to a separate thread. Let's close this issue now.

**Comment by emilemathieu** [comment]
Eventually I set `gid=0` in that case others `updategid` didn't update anything. This has been pushed in master.
