### ISSUE TITLE
[Core.VarInfo] Remove `VarInfo.index`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#388]
See https://github.com/yebai/Turing.jl/issues/367#issuecomment-345840292

**Comment by emilemathieu** [comment]
This PR https://github.com/yebai/Turing.jl/pull/395 removes  `VarInfo.index`

**Comment by emilemathieu** [comment]
PR https://github.com/yebai/Turing.jl/pull/395 merged
