### ISSUE TITLE
[Core.VarInfo] Allow adding right-hand-side information to `VarName`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#389]
The current `VarName` in `VarInfo` is only dependent on left-hand-side information, we might want to generalise this to include RHS information to distinguish variables with the same symbol but live in a different scope. A example design could be 

```julia
x ~ Normal(0,1; lhs_vn = unique_id)
```

**Comment by xukai92** [comment]
I think a solution is to introduce another filed to `VarInfo` named `mark`, and introduce different codes to mark variables. This also solves https://github.com/yebai/Turing.jl/issues/391 as now we can mark then can deleted variables.

**Comment by xukai92** [comment]
Closed by #407
