### ISSUE TITLE
[Core.Traces] Merge `TraceR` and `TraceC`.

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#392]
The original motivation for keeping two trace types is to distinguish between traces that store replaying information and traces that do not. However, since the introduction of `VarInfo`, replaying is always stored in `VarInfo`regardless of trace types. Therefore there is no point in keep separate trace types.

**Comment by emilemathieu** [comment]
@yebai do we agree that the only useful case of `forkr` is when it is called via `fork2` at the beggining of a `CSMC` sweep ? Otherwise `forkc` should be used since it's more efficient ?

**Comment by yebai** [comment]
> @yebai do we agree that the only useful case of forkr is when it is called via fork2 at the beggining of a CSMC sweep ? Otherwise forkc should be used since it's more efficient ?

That's right - the only use case for `forkr` is implementing the reference particle at the moment.

**Comment by emilemathieu** [comment]
@yebai could I do this in PR https://github.com/yebai/Turing.jl/pull/395 ?

**Comment by yebai** [comment]
Yes please go ahead - I will provide detailed feedback on the PR.

**Comment by emilemathieu** [comment]
I've merged `TraceC` and `TraceR` in the last commit https://github.com/yebai/Turing.jl/pull/395/commits/aac3fcdf6cfc12e3ab516b61d4a8de4bf4c6735b of my PR https://github.com/yebai/Turing.jl/pull/395.

**Comment by emilemathieu** [comment]
PR https://github.com/yebai/Turing.jl/pull/395 merged

**Comment by yebai** [comment]
> I've merged TraceC and TraceR in the last commit aac3fcd of my PR #395.

Good work - the code in #395 looks all correct to me!
