### ISSUE TITLE
Improve Turing website - turing.ml

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#403]

**Comment by xukai92** [comment]
What kind of points?

**Comment by yebai** [comment]
Sorry - I will post the details later. I created this issue and #402 to remind myself.

**Comment by gulgit** [comment]
Am just learning Bayesian Analysis, and wondering if I can contribute something on developing few illustrations.

**Comment by xukai92** [comment]
You can do it in a notebook and submit it in PR for that purpose. I can later link the notebook in the wiki

**Comment by xukai92** [comment]
@gulgit There are some notebook examples here https://github.com/yebai/Turing.jl/tree/master/example-models/notebooks

**Comment by yebai** [comment]
I made some (big) changes to our website. We now have a new domain name [turing.ml](turing.ml). The website is now built based on `jekyll`, which means we can write the pages using markdown (see `docs/index.md`). The hope is to create a easier approach for improving the website and documentations. 

cc: @xukai92 @emilemathieu
