### ISSUE TITLE
posterior prediction

### ISSUE THREAD

**Issue by drbenvincent** [yebai/Turing.jl#411]
Hi. Awesome package. Just starting to get to grips with it (and Julia). So far I've got some basic stuff happening, making inferences based on data. 

```julia
@model coin_flip(k, T) = begin
    # prior
    p ~ Uniform(0,1)
    # likelihood
    k ~ Binomial(T,p) 
    # posterior prediction
    k_pred = rand(Binomial(T,p))
    return p, k_pred
end

samples = sample( coin_flip(80,100), PG(50,300))
describe(samples)
```

gives me a fairly sensible output

```
Iterations = 1:300
Thinning interval = 1
Chains = 1
Samples per chain = 300

Empirical Posterior Estimates:
            Mean         SD       Naive SE        MCSE        ESS   
      p 0.793268703 0.039096518 0.0022572385 0.00234021945 279.10203
elapsed 0.002218118 0.010108722 0.0005836273 0.00080982430 155.81559
     lp 0.000000000 0.000000000 0.0000000000 0.00000000000       NaN

Quantiles:
            2.5%         25.0%       50.0%        75.0%        97.5%   
      p 0.7124110617 0.7699089885 0.796591786 0.8189613249 0.8616043969
elapsed 0.0011862382 0.0012289613 0.001256014 0.0012923468 0.0053516883
     lp 0.0000000000 0.0000000000 0.000000000 0.0000000000 0.0000000000
```

But I'm having issues with posterior prediction. I'm attempting to generate sample data `k_pred` in the model specification, but this variable is just not returned into the samples object. Am I doing something wrong, or is this just completely not how posterior prediction is dealt with in Turing?

**Comment by xukai92** [comment]
The `sample` function in Turing.jl returns posterior samples, i.e `θ ~ p(θ|D)`, and you need to deal with posterior prediction by yourself.

From your code I guess what you can do is

```julia
@model coin_flip(k, T) = begin
    # prior
    p ~ Uniform(0,1)
    # likelihood
    k ~ Binomial(T,p) 
end

chain = sample(coin_flip(80, 100), PG(50, 300))
p_samples = chain[:p]

# do something with your posterior samples in p_samples ...
```

**Comment by drbenvincent** [comment]
Ah, I understand now.

I was coming from a background using JAGS where the model spec defines the full joint, which you can then use in various ways depending on what you provide as observed and what you want to monitor. 

But your answer this makes sense - thanks.
