### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [yebai/Turing.jl#416]
This needs a new tag in order to support https://github.com/JuliaDiffEq/DiffEqBayes.jl/pull/14

**Comment by ChrisRackauckas** [comment]
bump

**Comment by xukai92** [comment]
Does all I need to do is tag it in GitHub?

**Comment by ChrisRackauckas** [comment]
If attobot is setup, yes. (and I'd recommend doing this often so that way people can use all of your hard work!)

**Comment by xukai92** [comment]
It seems that we're not allowed to give a minor release for a version support change (https://github.com/JuliaLang/METADATA.jl/pull/12049)? I'm not familiar with how tagging works. Can you give me some help here?

**Comment by ChrisRackauckas** [comment]
I commented. Hope that helps.

**Comment by xukai92** [comment]
NOTE: tag PR https://github.com/JuliaLang/METADATA.jl/pull/12791

**Comment by ChrisRackauckas** [comment]
Merged.
