### ISSUE TITLE
Stop supporting vectorized notation

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#425]
The `a ~ [dist]` notations seem no speed-up against to loop now (according to the test in `sampler.jl/vec_assume_mv.jl`). May be we can stop supporting it.

**Comment by yebai** [comment]
@xukai92 Is this only true for ReverseDiff? Or true for both forward and backward autodiff?

**Comment by xukai92** [comment]
I re-investigated into this issue and found I was wrong. The thing is some of the distributions can benefit from this vectorization but some not. I guess it's related to how the corresponding `logpdf` is implemented. But anyway let's keep it.
