### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by hessammehr** [yebai/Turing.jl#444]
The current tagged release is over 4 months old. Do we have a timeline for tagging a new release? I am mainly asking because Turing 0.4 requires a build environment on Windows, which is not ideal.

**Comment by yebai** [comment]
@hessammehr I've tagged a new release 0.4.1 - should get accepted as soon as auto tests are done. 

https://github.com/JuliaLang/METADATA.jl/pull/14680

**Comment by hessammehr** [comment]
Wonderful, new users will appreciate this!
