### ISSUE TITLE
MCMC output 

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#56]
The current form for reporting MCMC output is a bit arbitrary.  It makes sense to standardise the output and report results in the form of joint posterior. 

It's also helpful to implement some utility functions for the Chain type for inspecting samples from various MCMC samplers, e.g.:

IAT: integrated autocorrelation time: http://search.r-project.org/library/LaplacesDemon/html/IAT.html
ESS: effective sample size: http://search.r-project.org/library/LaplacesDemon/html/ESS.html
MCSE: Monte Carlo standard error: http://search.r-project.org/library/LaplacesDemon/html/MCSE.html

PS. The [Mamba.jl](http://mambajl.readthedocs.org/en/latest/) package has a format for reporting Monte Carlo results. It is also the default format for [Stan.jl](https://github.com/goedman/Stan.jl). But we might need to adapt this format to store sample weights.

**Comment by xukai92** [comment]
In addition to these features, let's also add a verbose flag to control the intermediate sampling info (like [PG]: Iter ...), which can lead to clear test log by turning it off in tests.

**Comment by xukai92** [comment]
I adapted the code from `Mamba.jl` for MCSE and ESS (#74). Do you have a reference for IAT in detail? (or maybe I don't really need it as we already have ess).

**Comment by yebai** [comment]
I've merged this PR. 

We don't really need IAT for now - I have a plan to use Mamba's `Chain` type to store Turing's MCMC output. It will allow us to share summary statistics functions and plotting utilities from the Mamba package systematically. We can talk more about this later and maybe implement it in the next release.

**Comment by yebai** [comment]
Closed by PR #90
