### ISSUE TITLE
The hierarchy of samplers

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#62]
I wonder if we should create a better hierarchy for samplers. The current was seems a bit arbitrary: we use `ParticleSampler` in the default sample function and overload some in their own place (IS and HMC). Also, when I split AD from HMC, I put the type of sampler it can accept as `GradientSampler`, which could be meaningful for future work.

Shall we try to design something like this:

```julia
abstract Sampler{T<:InferenceAlgorithm}
abstract ParticleSampler{T} <: Sampler{T}
abstract GradientSampler{T} <: Sampler{T}
type ImportanceSampler{IS} <: ParticleSampler{IS}
  ...
end
type SMCSampler{SMC} <: ParticleSampler{SMC}
  ...
end
type PGSampler{PG} <: ParticleSampler{PG}
  ...
end
type HMCSampler{HMC} <: GradientSampler{T}
  ...
end
```

**Comment by yebai** [comment]
The main purpose of the sampler hierarchy is to correctly dispatch `assume` and `observe` calls. Since we are replacing these methods in #55, we might be able remove this hierarchy when #55 is done.

**Comment by xukai92** [comment]
I see. It makes sense. And for my problem we've already decomposed AD from samplers so it is also solved. I guess we can close this issue now.
