### ISSUE TITLE
HMC: add pre-conditioning (mass) matrix

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#67]
For discussion of error caused by large step size  here: https://github.com/yebai/Turing.jl/pull/66#issuecomment-267395730

**Comment by xukai92** [comment]
The transformation we found last time that causes numerical overflow is exp()/log() for positive numbers. When we move in R towards a larger value, and call exp() to convert back to X, the numerical overflow occurs.

Do you think it is feasible we just use another transform for positive numbers? Say:

- x -> x, for x >= 1
- x -> log(x), for x < 1

This function is still continuous as both log(x) and x has the same derivative at x = 1, and will not cause numerical overflow. But I'm not sure if it will broken the leapfrog integration?

**Comment by yebai** [comment]
There are two variables that determines how far HMC travels in each dimension, namely the `momentum` variable and `n_step*ϵ`. It is probably better to first try introducing a pre-conditioning mass matrix and see whether it helps resolving the large step size issue.

**Comment by xukai92** [comment]
Zoubin said it's probably better to run 10 chains of 100 samples instead of 1 chain of 1000 samples to compute the pre-conditioning matrix.

**Comment by xukai92** [comment]
@yebai Are you working on this? If not I'd like to pick it up and work on it.

**Comment by xukai92** [comment]
@yebai Page 47 of the CmdStan handbook refers the three mode of pre-cond in Stan as "unit", "diag" and "dense". I guess "unit" just means without pre-cond, "diag" is diagonal of the co-variance and "dense" is probably using full co-variance. Is my understanding correct?

**Comment by yebai** [comment]
yes, that's correct.

**Comment by yebai** [comment]
Let's do the `dense` preconditioning matrix in the future.

**Comment by xukai92** [comment]
Closed in favour of https://github.com/yebai/Turing.jl/issues/279
