### ISSUE TITLE
Automated benchmarking for Gibbs, HMC

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#7]
We need to write some automated benchmarking scripts for Turing. These benchmarking scripts can include both running time and predictive performance comparisons. We can also compare to other systems like [Anglican](http://www.robots.ox.ac.uk/~fwood/anglican/), [LibBi](http://libbi.org/).

**Comment by xukai92** [comment]
My banchmarking script is located at: https://github.com/xukai92/TuringBenchmarking

**Comment by xukai92** [comment]
I'm going to look into using `BenchmarkTools.jl` to do this.

**Comment by yebai** [comment]
Looks good!

PS. another tool for benchmarking https://github.com/lindahua/BenchmarkLite.jl . This package might be simpler to use and is the benchmarking tool used by Distributions.jl

**Comment by yebai** [comment]
Ref: #117

**Comment by yebai** [comment]
Closed by #121; more benchmarking is in #131
