### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by datnamer** [yebai/Turing.jl#71]
Hello,

Great package. I have some questions if anyone has a second.

1. Is there a posterior predictive check method? 
2. Can the random variables be used in any arbitrary julia function? 
3. Are there plans for variational inference?
4. Have you done any benchmarking vs stan? 
5. How does stochastic control flow work from the user perspective? 

Thanks!

**Comment by xukai92** [comment]
Hi,

Thanks for you questions.

1. Not now - but it will be available just in the next release.
2. Yes - you can plug arbitrary *pure* Julia function, i.e. function does not simply call some external Python/C++ libraries
3. Not now - we currently focus on sampling methods
@yebal Do you have plan for VI?
4. Not for the current version - the current implementation of gradient based method is not comparable to Stan, we are still developing it; the implementation of importance sampling based method (i.e., IS, SMC and PG) shows state-of-the-art performance. 
@yebai is the benchmarking vs Prob C and Anglican available online now?
5. You can simply use random variable in control flow conditions. Here is a simple example
```julia
@model scf begin
  @assume m ~ Normal(0, 10)
  if m < 0
    @assume s ~ Gamma(2, 3)
  else
    @assume s ~ Gamma(4, 6)
  end
  @observe 1.1 ~ Normal(m, s)
  @observe 2.3 ~ Normal(m, s)
  @predict s m
end
```

**Comment by datnamer** [comment]
Very cool, thanks.  Maximum a posteriori would be of interest to simulate max likelihood methods.

**Comment by yebai** [comment]
> Maximum a posteriori would be of interest to simulate max likelihood methods.

It is a good suggestion. I've created a feature request #72 for this, check it back later.  

> Are there plans for variational inference?

So far we've been focusing on sampling methods for inference.  The work on VI has been discussed but we haven't got a concrete plan yet. It would be interesting to see some more detailed suggestions here.

**Comment by yebai** [comment]
I'm going to close this issue now. Maybe we can a Q&A thread in the future.
