### ISSUE TITLE
Further work for the Gibbs PR

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#77]
### Discussion

- ~we need a consistent output of model (i.e. return) and storage of predicts~
- ~we need to discuss the consistent way of using task.storage~

### Enhancement

- [x] the naming issue of x[i,j,k] and x[i,j][k]
- [x] allow user to step how many steps each sampler in Gibbs sampling is run
- ~the current implementation has a bad performance (speed)~
- ~unify the way of storing and producing variables~

**Comment by yebai** [comment]
It seems the HMC sampler constructor is broken. Running the following code would throw an error

```julia
HMC(1000, 0.2, 5)
```

**Comment by xukai92** [comment]
Which version (commit) do you meet this error?

**Comment by xukai92** [comment]
Do you think it's better to keep both `VarInfo` and `Sample` and convert between them when necessary or use one data structure only?

**Comment by yebai** [comment]
> Which version (commit) do you meet this error?

It is working now with the most recent `new-interface`. I might be using some intermediate commit.

> Do you think it's better to keep both VarInfo and Sample and convert between them when necessary or use one data structure only?

It makes sense to unify these data structures. However, let's focus on bug fixing and make it a TODO item for the next release.
