### ISSUE TITLE
Make a `readthedoc` website.

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#9]
Create a readthedoc website, see e.g. [Distributions](https://github.com/JuliaStats/Distributions.jl/tree/master/doc)

**Comment by xukai92** [comment]
I just initialise the readthedoc here: https://github.com/xukai92/Turing.jl/tree/docs/docs.

**Comment by yebai** [comment]
@xukai92 looks nice - thanks, Kai! Can you merge your repo with the main Turing repo, by e.g. putting everything inside your repo under `doc/`?
