### ISSUE TITLE
Refactoring code: Unify VarInfo, Trace, TaskStorage, Chain.

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#96]
At the moment, we have various data structures that stores intermediate (MCMC) sampling states. It probably makes sense to unify these data structures. 

(I don't have a complete idea how to do this yet, but let's start thinking about this issue and post ideas here.)

**Comment by yebai** [comment]
Here is a (preliminary) plan that we have discussed:


- Update VarInfo:  Remove Var, instead store MCMC state in a flatten data structure (similar to Mamba’s Chain type)
- Update internal variable naming scheme: 
    - x[1,2,3] ==> x[i]   where i is linear index corresponding to [1,2,3] (e.g. sub2ind(dims, i, j, k...) -> index)
    - x[1][2][..]  ==> x[i][j][..]  (the nesting could continue N times)
    - Forbid variables with same name, with the exception 
        - loops, e.g. `for i=1:N,   x ~ Normal(0,1);  end`
        - recursions, e.g.  `f(x) = if x > 1, f(x-1); else x ~ Normal(0,1); end`
        - Note the following case is forbidden:   `f() = begin x ~ Normal(0,1); y ~ Normal(0,1) end`
- Remove predict, `~` will store MCMC state by default.
- Gradually merge Trace into VarInfo (maybe keep Trace as a field of VarInfo initially)

**Comment by xukai92** [comment]
Note: We tend to store variables in their original space.

**Comment by xukai92** [comment]
Note: I will next resolve the 2nd and 3rd points together by the following steps:
1. Change code to store untransformed variables in `VarInfo`
2. Remove `@predict` (with `@~` store variables into `VarInfo`)
3. Remove the use of `Sample` (as it's only copy things from `@predict`)

**Comment by xukai92** [comment]
It seems that it's impractical to remove the use of `Task.storage` because IS-based algorithms will need variable information tied to task level.

**Comment by xukai92** [comment]
@yebai Do you think it's better to move `predict()` into `@model` level instead of calling it in each `@~`?

**Comment by yebai** [comment]
Ref #142;

**Comment by xukai92** [comment]
I created an individual issue (https://github.com/yebai/Turing.jl/issues/146) for the naming stuff. Do you think we can close this one now?

**Comment by yebai** [comment]
Fixed by #114, #108, #103.
